/**
 * PM2 для VPS (/opt/solana-alpha) после W1/W2 slim.
 * Дашборд + W6.1 DEX collectors (все пять тиков по умолчанию 60s) + W6.3a paper skeleton (stream/parser/atlas выключены).
 *
 * Запуск новых процессов только точечно:
 *   pm2 start ecosystem.config.cjs --only sa-pumpswap
 * Не использовать массовый `pm2 start ecosystem.config.cjs` без `--only` — поднимет всё из списка.
 */
const path = require('path');
const root = __dirname;

module.exports = {
  apps: [
    {
      name: 'dashboard-organizer-paper',
      cwd: root,
      script: 'npm',
      args: 'run --silent dashboard',
      interpreter: 'none',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      merge_logs: true,
      time: true,
      env: {
        HOST: '0.0.0.0',
        PORT: '3008',
        STORE_PATH: path.join(root, 'data/paper2/organizer-paper.jsonl'),
      },
    },
    {
      name: 'sa-raydium',
      cwd: root,
      script: 'scripts-tmp/raydium-collector.mjs',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      max_memory_restart: '300M',
      merge_logs: true,
      time: true,
      env: { NODE_ENV: 'production' },
    },
    {
      name: 'sa-meteora',
      cwd: root,
      script: 'scripts-tmp/meteora-collector.mjs',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      max_memory_restart: '300M',
      merge_logs: true,
      time: true,
      env: { NODE_ENV: 'production' },
    },
    {
      name: 'sa-orca',
      cwd: root,
      script: 'scripts-tmp/orca-collector.mjs',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      max_memory_restart: '300M',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        /** Explicit 60s — PM2 may retain removed keys across reload; override stale dump. */
        ORCA_COLLECTOR_INTERVAL_MS: '60000',
      },
    },
    {
      name: 'sa-moonshot',
      cwd: root,
      script: 'scripts-tmp/moonshot-collector.mjs',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      max_memory_restart: '300M',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        MOONSHOT_COLLECTOR_INTERVAL_MS: '60000',
      },
    },
    {
      name: 'sa-pumpswap',
      cwd: root,
      script: 'scripts-tmp/pumpswap-collector.mjs',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      max_memory_restart: '300M',
      merge_logs: true,
      time: true,
      env: { NODE_ENV: 'production' },
    },
    {
      name: 'sa-collector-watch',
      cwd: root,
      script: 'scripts-tmp/collector-log-watch.mjs',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      max_memory_restart: '120M',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        /** TELEGRAM_* из .env. Один чат: [ALERT][dex_collectors] — 429, тики, сеть, tick failed, fatal. */
        COLLECTOR_WATCH_POLL_MS: '15000',
      },
    },
    {
      name: 'sa-jupiter',
      cwd: root,
      script: 'scripts-tmp/jupiter-route-watcher.mjs',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      max_memory_restart: '350M',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        JUPITER_WATCHER_ENQUEUE_RPC: '0',
      },
    },
    {
      name: 'sa-direct-lp',
      cwd: root,
      script: 'scripts-tmp/direct-lp-detector.mjs',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      max_memory_restart: '300M',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        DIRECT_LP_ENQUEUE_RPC: '0',
      },
    },
    {
      name: 'pt1-diprunner',
      cwd: root,
      script: 'npm',
      args: 'run --silent papertrader',
      interpreter: 'none',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 30,
      restart_delay: 5000,
      max_memory_restart: '400M',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        PAPER_STRATEGY_ID: 'pt1-diprunner',
        PAPER_STRATEGY_KIND: 'dip',
        PAPER_TRADES_PATH: path.join(root, 'data/paper2/pt1-diprunner.jsonl'),
        PAPER_HEARTBEAT_INTERVAL_MS: '30000',
        PAPER_DISCOVERY_INTERVAL_MS: '10000',
        PAPER_TRACK_INTERVAL_MS: '30000',
        PAPER_FOLLOWUP_TICK_MS: '60000',
        PAPER_DRY_RUN: 'false',
        PAPER_POSITION_USD: '100',
        PAPER_SAFETY_CHECK_ENABLED: '0',
        PAPER_PRIORITY_FEE_ENABLED: '1',
        PAPER_LIVE_MCAP_TTL_MS: '30000',

        PAPER_ENABLE_LAUNCHPAD_LANE: 'false',
        PAPER_ENABLE_MIGRATION_LANE: 'false',
        PAPER_ENABLE_POST_LANE: 'true',
        PAPER_POST_MIN_AGE_MIN: '180',
        PAPER_POST_MAX_AGE_MIN: '0',
        PAPER_POST_MIN_LIQ_USD: '50000',
        PAPER_POST_MIN_VOL_5M_USD: '10000',
        PAPER_POST_MIN_BUYS_5M: '4',
        PAPER_POST_MIN_SELLS_5M: '3',
        PAPER_POST_MIN_BS: '0.98',
        PAPER_MIN_HOLDER_COUNT: '2000',

        PAPER_DIP_LOOKBACK_MIN: '120',
        PAPER_DIP_LOOKBACK_WINDOWS_MIN: '120,360,720',
        PAPER_DIP_MIN_DROP_PCT: '-15',
        PAPER_DIP_MAX_DROP_PCT: '-50',
        PAPER_DIP_MIN_IMPULSE_PCT: '12',
        PAPER_DIP_MIN_AGE_MIN: '0',
        PAPER_DIP_COOLDOWN_MIN: '120',
        PAPER_DIP_COOLDOWN_MIN_SCALP: '20',

        PAPER_DCA_LEVELS: '-10:0.3,-20:0.3',
        PAPER_DCA_KILLSTOP: '-0.40',
        PAPER_TP_LADDER: '0.10:0.40,0.20:0.50,0.30:0.80,0.40:1.0',
        PAPER_TP_X: '100',
        PAPER_SL_X: '0',
        PAPER_TRAIL_MODE: 'ladder_retrace',
        PAPER_TRAIL_DROP: '0.10',
        PAPER_TRAIL_TRIGGER_X: '1.10',
        PAPER_TIMEOUT_HOURS: '24',
        PAPER_PEAK_LOG_STEP_PCT: '1',

        PAPER_DIP_WHALE_ANALYSIS_ENABLED: '1',
        PAPER_DIP_REQUIRE_WHALE_TRIGGER: '0',
        PAPER_DIP_LARGE_SELL_USD: '3000',
        PAPER_DIP_RECENT_LOOKBACK_MIN: '10',
        PAPER_DIP_CAPITULATION_PCT: '0.7',
        PAPER_DIP_WHALE_SILENCE_MIN: '10',
        PAPER_DIP_GROUP_SELL_USD: '5000',
        PAPER_DIP_GROUP_MIN_SELLERS: '2',
        PAPER_DIP_GROUP_DUMP_PCT: '0.4',
        PAPER_DIP_BLOCK_CREATOR_DUMP: '1',
        PAPER_DIP_CREATOR_DUMP_LOOKBACK_MIN: '20',
        PAPER_DIP_CREATOR_DUMP_MIN_PCT: '0.05',
        PAPER_DIP_CREATOR_DUMP_MAX_PCT: '0.6',
        PAPER_DIP_DCA_PRED_MIN_SELLS_24H: '4',
        PAPER_DIP_DCA_PRED_MIN_INTERVAL_MIN: '30',
        PAPER_DIP_DCA_PRED_MIN_CHUNK_USD: '3000',
        PAPER_DIP_DCA_AGGR_MIN_SELLS_24H: '6',
        PAPER_DIP_DCA_AGGR_MAX_INTERVAL_MIN: '15',

        PAPER_HOLDERS_LIVE_ENABLED: '1',
        PAPER_HOLDERS_USE_QN_ADDON: '0',
        PAPER_HOLDERS_TTL_MS: '90000',
        PAPER_HOLDERS_NEG_TTL_MS: '15000',
        PAPER_HOLDERS_MAX_PER_TICK: '10',
        PAPER_HOLDERS_TIMEOUT_MS: '4000',
        PAPER_HOLDERS_INCLUDE_TOKEN2022: '1',
        PAPER_HOLDERS_ON_FAIL: 'db_fallback',
        PAPER_HOLDERS_DB_WRITEBACK: '1',
        PAPER_HOLDERS_GPA_CREDITS_PER_CALL: '100',
        QN_FEATURE_BUDGET_HOLDERS: '10000000',

        PAPER_PRICE_VERIFY_ENABLED: '1',
        PAPER_PRICE_VERIFY_BLOCK_ON_FAIL: '1',
        PAPER_PRICE_VERIFY_USE_JUPITER_PRICE: '0',
        PAPER_PRICE_VERIFY_MAX_SLIP_PCT: '4.0',
        PAPER_PRICE_VERIFY_MAX_SLIP_BPS: '400',
        PAPER_PRICE_VERIFY_MAX_PRICE_IMPACT_PCT: '8.0',
        PAPER_PRICE_VERIFY_TIMEOUT_MS: '2500',

        /* W7.6 impulse confirm — default off; rolling 6h QN kill + Telegram at IMPULSE_QN_ROLLING_MAX_CREDITS */
        PAPER_IMPULSE_CONFIRM_ENABLED: '1',
        PAPER_IMPULSE_DIP_POLICY: 'parallel_and',
        PAPER_IMPULSE_PG_MIN_DROP_PCT: '5',
        PAPER_IMPULSE_RPC_MAX_PER_MIN: '30',
        QN_FEATURE_BUDGET_IMPULSE_CONFIRM: '5000000',
        IMPULSE_QN_ROLLING_MAX_CREDITS: '1000000',

        /* W7.5 §10.5 — full rollout (liquidity drain watch) */
        PAPER_LIQ_WATCH_ENABLED: '1',
        PAPER_LIQ_WATCH_FORCE_CLOSE: '1',
        PAPER_LIQ_WATCH_DRAIN_PCT: '35',
        PAPER_LIQ_WATCH_MIN_AGE_MIN: '1',
        PAPER_LIQ_WATCH_CONSECUTIVE_FAILURES: '2',
        PAPER_LIQ_WATCH_SNAPSHOT_MAX_AGE_MS: '120000',
        PAPER_LIQ_WATCH_RPC_FALLBACK: '0',
        PAPER_LIQ_WATCH_STAMP_ON_ALL_CLOSE: '1',
        PAPER_LIQ_WATCH_STAMP_ON_TRACK: '0',
      },
    },
    {
      name: 'pt1-oscar',
      cwd: root,
      script: 'npm',
      args: 'run --silent papertrader',
      interpreter: 'none',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 30,
      restart_delay: 5000,
      max_memory_restart: '400M',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        PAPER_STRATEGY_ID: 'pt1-oscar',
        PAPER_STRATEGY_KIND: 'dip',
        PAPER_TRADES_PATH: path.join(root, 'data/paper2/pt1-oscar.jsonl'),
        PAPER_HEARTBEAT_INTERVAL_MS: '30000',
        PAPER_DISCOVERY_INTERVAL_MS: '10000',
        PAPER_TRACK_INTERVAL_MS: '30000',
        PAPER_FOLLOWUP_TICK_MS: '60000',
        PAPER_DRY_RUN: 'false',
        PAPER_POSITION_USD: '100',
        PAPER_SAFETY_CHECK_ENABLED: '1',
        PAPER_PRIORITY_FEE_ENABLED: '1',
        PAPER_PRIORITY_FEE_TICKER_MS: '60000',
        PAPER_PRIORITY_FEE_MAX_AGE_MS: '600000',
        PAPER_PRIORITY_FEE_RPC_TIMEOUT_MS: '2500',
        PAPER_PRIORITY_FEE_PERCENTILE: 'p75',
        PAPER_PRIORITY_FEE_TARGET_CU: '200000',
        PAPER_PRIORITY_FEE_CACHE_PATH: path.join(root, 'data/priority-fee-cache.json'),
        PAPER_LIVE_MCAP_TTL_MS: '30000',

        PAPER_ENABLE_LAUNCHPAD_LANE: 'false',
        PAPER_ENABLE_MIGRATION_LANE: 'false',
        PAPER_ENABLE_POST_LANE: 'true',
        PAPER_POST_MIN_AGE_MIN: '120',
        PAPER_POST_MAX_AGE_MIN: '0',
        PAPER_POST_MIN_LIQ_USD: '25000',
        PAPER_POST_MIN_VOL_5M_USD: '10000',
        PAPER_POST_MIN_BUYS_5M: '4',
        PAPER_POST_MIN_SELLS_5M: '3',
        PAPER_POST_MIN_BS: '0.98',
        PAPER_MIN_HOLDER_COUNT: '1500',

        PAPER_DIP_LOOKBACK_MIN: '120',
        PAPER_DIP_LOOKBACK_WINDOWS_MIN: '120,360,720',
        PAPER_DIP_MIN_DROP_PCT: '-15',
        PAPER_DIP_MAX_DROP_PCT: '-50',
        PAPER_DIP_MIN_IMPULSE_PCT: '12',
        PAPER_DIP_MIN_AGE_MIN: '0',
        PAPER_DIP_COOLDOWN_MIN: '120',
        PAPER_DIP_COOLDOWN_MIN_SCALP: '20',

        PAPER_DCA_LEVELS: '-7:0.3,-14:0.3',
        PAPER_DCA_KILLSTOP: '-0.25',
        PAPER_TP_LADDER: '0.10:0.30,0.20:0.50,0.30:1.0',
        PAPER_TP_X: '100',
        PAPER_SL_X: '0',
        PAPER_TRAIL_MODE: 'ladder_retrace',
        PAPER_TRAIL_DROP: '0.10',
        PAPER_TRAIL_TRIGGER_X: '1.10',
        PAPER_TIMEOUT_HOURS: '12',
        PAPER_PEAK_LOG_STEP_PCT: '1',

        PAPER_DIP_WHALE_ANALYSIS_ENABLED: '1',
        PAPER_DIP_REQUIRE_WHALE_TRIGGER: '0',
        PAPER_DIP_LARGE_SELL_USD: '3000',
        PAPER_DIP_RECENT_LOOKBACK_MIN: '10',
        PAPER_DIP_CAPITULATION_PCT: '0.7',
        PAPER_DIP_WHALE_SILENCE_MIN: '10',
        PAPER_DIP_GROUP_SELL_USD: '5000',
        PAPER_DIP_GROUP_MIN_SELLERS: '2',
        PAPER_DIP_GROUP_DUMP_PCT: '0.4',
        PAPER_DIP_BLOCK_CREATOR_DUMP: '1',
        PAPER_DIP_CREATOR_DUMP_LOOKBACK_MIN: '20',
        PAPER_DIP_CREATOR_DUMP_MIN_PCT: '0.05',
        PAPER_DIP_CREATOR_DUMP_MAX_PCT: '0.6',
        PAPER_DIP_DCA_PRED_MIN_SELLS_24H: '4',
        PAPER_DIP_DCA_PRED_MIN_INTERVAL_MIN: '30',
        PAPER_DIP_DCA_PRED_MIN_CHUNK_USD: '3000',
        PAPER_DIP_DCA_AGGR_MIN_SELLS_24H: '6',
        PAPER_DIP_DCA_AGGR_MAX_INTERVAL_MIN: '15',

        PAPER_HOLDERS_LIVE_ENABLED: '1',
        PAPER_HOLDERS_USE_QN_ADDON: '0',
        PAPER_HOLDERS_TTL_MS: '90000',
        PAPER_HOLDERS_NEG_TTL_MS: '15000',
        PAPER_HOLDERS_MAX_PER_TICK: '10',
        PAPER_HOLDERS_TIMEOUT_MS: '4000',
        PAPER_HOLDERS_INCLUDE_TOKEN2022: '1',
        PAPER_HOLDERS_ON_FAIL: 'db_fallback',
        PAPER_HOLDERS_DB_WRITEBACK: '1',
        PAPER_HOLDERS_GPA_CREDITS_PER_CALL: '100',
        QN_FEATURE_BUDGET_HOLDERS: '10000000',

        PAPER_PRICE_VERIFY_ENABLED: '1',
        PAPER_PRICE_VERIFY_BLOCK_ON_FAIL: '1',
        PAPER_PRICE_VERIFY_USE_JUPITER_PRICE: '0',
        PAPER_PRICE_VERIFY_MAX_SLIP_PCT: '4.0',
        PAPER_PRICE_VERIFY_MAX_SLIP_BPS: '400',
        PAPER_PRICE_VERIFY_MAX_PRICE_IMPACT_PCT: '8.0',
        PAPER_PRICE_VERIFY_TIMEOUT_MS: '2500',

        PAPER_IMPULSE_CONFIRM_ENABLED: '1',
        PAPER_IMPULSE_DIP_POLICY: 'parallel_and',
        PAPER_IMPULSE_PG_MIN_DROP_PCT: '5',
        PAPER_IMPULSE_RPC_MAX_PER_MIN: '30',
        QN_FEATURE_BUDGET_IMPULSE_CONFIRM: '5000000',
        IMPULSE_QN_ROLLING_MAX_CREDITS: '1000000',

        /* W7.5 §10.5 — full rollout (pt1-oscar) */
        PAPER_LIQ_WATCH_ENABLED: '1',
        PAPER_LIQ_WATCH_FORCE_CLOSE: '1',
        PAPER_LIQ_WATCH_DRAIN_PCT: '35',
        PAPER_LIQ_WATCH_MIN_AGE_MIN: '1',
        PAPER_LIQ_WATCH_CONSECUTIVE_FAILURES: '2',
        PAPER_LIQ_WATCH_SNAPSHOT_MAX_AGE_MS: '120000',
        PAPER_LIQ_WATCH_RPC_FALLBACK: '0',
        PAPER_LIQ_WATCH_STAMP_ON_ALL_CLOSE: '1',
        PAPER_LIQ_WATCH_STAMP_ON_TRACK: '0',
      },
    },
    {
      name: 'pt1-dno',
      cwd: root,
      script: 'npm',
      args: 'run --silent papertrader',
      interpreter: 'none',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 30,
      restart_delay: 5000,
      max_memory_restart: '400M',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        PAPER_STRATEGY_ID: 'pt1-dno',
        PAPER_STRATEGY_KIND: 'dip',
        PAPER_TRADES_PATH: path.join(root, 'data/paper2/pt1-dno.jsonl'),
        PAPER_HEARTBEAT_INTERVAL_MS: '30000',
        PAPER_DISCOVERY_INTERVAL_MS: '10000',
        PAPER_TRACK_INTERVAL_MS: '30000',
        PAPER_FOLLOWUP_TICK_MS: '60000',
        PAPER_DRY_RUN: 'false',
        PAPER_POSITION_USD: '100',
        /** DNO: шире поиск по снимкам + чаще переоценка mint внутри одного процесса */
        PAPER_SNAPSHOT_CANDIDATE_LIMIT: '900',
        PAPER_DISCOVERY_REEVAL_SEC: '30',
        PAPER_SAFETY_CHECK_ENABLED: '1',
        PAPER_PRIORITY_FEE_ENABLED: '1',
        PAPER_PRIORITY_FEE_TICKER_MS: '60000',
        PAPER_PRIORITY_FEE_MAX_AGE_MS: '600000',
        PAPER_PRIORITY_FEE_RPC_TIMEOUT_MS: '2500',
        PAPER_PRIORITY_FEE_PERCENTILE: 'p75',
        PAPER_PRIORITY_FEE_TARGET_CU: '200000',
        PAPER_PRIORITY_FEE_CACHE_PATH: path.join(root, 'data/priority-fee-cache.json'),
        PAPER_LIVE_MCAP_TTL_MS: '30000',

        PAPER_ENABLE_LAUNCHPAD_LANE: 'false',
        PAPER_ENABLE_MIGRATION_LANE: 'false',
        PAPER_ENABLE_POST_LANE: 'true',
        /* DNO entry — tighter pool than diprunner */
        PAPER_POST_MIN_AGE_MIN: '30',
        PAPER_POST_MAX_AGE_MIN: '0',
        PAPER_POST_MIN_LIQ_USD: '8000',
        PAPER_POST_MIN_VOL_5M_USD: '10000',
        PAPER_POST_MIN_BUYS_5M: '4',
        PAPER_POST_MIN_SELLS_5M: '3',
        PAPER_POST_MIN_BS: '0.98',
        PAPER_MIN_HOLDER_COUNT: '1000',

        PAPER_DIP_LOOKBACK_MIN: '120',
        /** Короткие окна первыми (сортировка в config): ловим резкие проливы на свежих парах */
        PAPER_DIP_LOOKBACK_WINDOWS_MIN: '15,30,120,360,720',
        PAPER_DIP_MIN_DROP_PCT: '-15',
        PAPER_DIP_MAX_DROP_PCT: '-50',
        PAPER_DIP_MIN_IMPULSE_PCT: '12',
        PAPER_DIP_MIN_AGE_MIN: '0',
        PAPER_DIP_COOLDOWN_MIN: '120',
        PAPER_DIP_COOLDOWN_MIN_SCALP: '20',

        /* DNO — single DCA −10% → +30% notional; kill −25% vs avg entry */
        PAPER_DCA_LEVELS: '-10:0.3',
        PAPER_DCA_KILLSTOP: '-0.25',
        /* TP ladder: each sellFraction applies to remaining position */
        PAPER_TP_LADDER: '0.05:0.30,0.10:0.50,0.15:0.80,0.20:1.0',
        PAPER_TP_X: '100',
        PAPER_SL_X: '0',
        /* ladder_retrace: exit TRAIL when PnL falls back below prior fired step */
        PAPER_TRAIL_MODE: 'ladder_retrace',
        PAPER_TRAIL_DROP: '0.10',
        PAPER_TRAIL_TRIGGER_X: '1.10',
        PAPER_TIMEOUT_HOURS: '2',
        PAPER_PEAK_LOG_STEP_PCT: '1',

        PAPER_DIP_WHALE_ANALYSIS_ENABLED: '1',
        PAPER_DIP_REQUIRE_WHALE_TRIGGER: '0',
        PAPER_DIP_LARGE_SELL_USD: '3000',
        PAPER_DIP_RECENT_LOOKBACK_MIN: '10',
        PAPER_DIP_CAPITULATION_PCT: '0.7',
        PAPER_DIP_WHALE_SILENCE_MIN: '10',
        PAPER_DIP_GROUP_SELL_USD: '5000',
        PAPER_DIP_GROUP_MIN_SELLERS: '2',
        PAPER_DIP_GROUP_DUMP_PCT: '0.4',
        PAPER_DIP_BLOCK_CREATOR_DUMP: '1',
        PAPER_DIP_CREATOR_DUMP_LOOKBACK_MIN: '20',
        PAPER_DIP_CREATOR_DUMP_MIN_PCT: '0.05',
        PAPER_DIP_CREATOR_DUMP_MAX_PCT: '0.6',
        PAPER_DIP_DCA_PRED_MIN_SELLS_24H: '4',
        PAPER_DIP_DCA_PRED_MIN_INTERVAL_MIN: '30',
        PAPER_DIP_DCA_PRED_MIN_CHUNK_USD: '3000',
        PAPER_DIP_DCA_AGGR_MIN_SELLS_24H: '6',
        PAPER_DIP_DCA_AGGR_MAX_INTERVAL_MIN: '15',

        PAPER_HOLDERS_LIVE_ENABLED: '1',
        PAPER_HOLDERS_USE_QN_ADDON: '0',
        PAPER_HOLDERS_TTL_MS: '90000',
        PAPER_HOLDERS_NEG_TTL_MS: '15000',
        PAPER_HOLDERS_MAX_PER_TICK: '40',
        PAPER_HOLDERS_TIMEOUT_MS: '4000',
        PAPER_HOLDERS_INCLUDE_TOKEN2022: '1',
        PAPER_HOLDERS_ON_FAIL: 'db_fallback',
        PAPER_HOLDERS_DB_WRITEBACK: '1',
        PAPER_HOLDERS_GPA_CREDITS_PER_CALL: '100',
        QN_FEATURE_BUDGET_HOLDERS: '10000000',

        PAPER_PRICE_VERIFY_ENABLED: '1',
        PAPER_PRICE_VERIFY_BLOCK_ON_FAIL: '1',
        PAPER_PRICE_VERIFY_USE_JUPITER_PRICE: '0',
        PAPER_PRICE_VERIFY_MAX_SLIP_PCT: '4.0',
        PAPER_PRICE_VERIFY_MAX_SLIP_BPS: '400',
        PAPER_PRICE_VERIFY_MAX_PRICE_IMPACT_PCT: '8.0',
        PAPER_PRICE_VERIFY_TIMEOUT_MS: '2500',

        PAPER_IMPULSE_CONFIRM_ENABLED: '1',
        PAPER_IMPULSE_DIP_POLICY: 'parallel_and',
        /** Δ между двумя PG-снимками пути импульса; было 5 — слишком чувствительно к шуму минутки */
        PAPER_IMPULSE_PG_MIN_DROP_PCT: '15',
        /** Live (QN Orca spot / Jupiter) vs якорь=pNew: только если цена в полосе −50%…−15% от снимка */
        PAPER_IMPULSE_MIN_DOWN_PCT_FROM_ANCHOR: '15',
        PAPER_IMPULSE_MAX_DOWN_PCT_FROM_ANCHOR: '50',
        PAPER_IMPULSE_RPC_MAX_PER_MIN: '30',
        QN_FEATURE_BUDGET_IMPULSE_CONFIRM: '5000000',
        IMPULSE_QN_ROLLING_MAX_CREDITS: '1000000',

        /* W7.5 §10.5 — full rollout (pt1-dno) */
        PAPER_LIQ_WATCH_ENABLED: '1',
        PAPER_LIQ_WATCH_FORCE_CLOSE: '1',
        PAPER_LIQ_WATCH_DRAIN_PCT: '35',
        PAPER_LIQ_WATCH_MIN_AGE_MIN: '1',
        PAPER_LIQ_WATCH_CONSECUTIVE_FAILURES: '2',
        PAPER_LIQ_WATCH_SNAPSHOT_MAX_AGE_MS: '120000',
        PAPER_LIQ_WATCH_RPC_FALLBACK: '0',
        PAPER_LIQ_WATCH_STAMP_ON_ALL_CLOSE: '1',
        PAPER_LIQ_WATCH_STAMP_ON_TRACK: '0',
      },
    },
  ],
};
