/** VPS `/opt/solana-alpha`: Живой Оскар + дашборд + сборщики снимков (PM2 читает этот файл). */
const path = require('path');
const root = __dirname;

module.exports = {
  apps: [
    {
      name: 'live-oscar-dashboard',
      cwd: root,
      /**
       * Не `npm run dashboard`: PM2 держит PID npm/tsx-обёртки — при `reload` слушатель на PORT может
       * не успеть освободиться → EADDRINUSE и тысячи рестартов. Прямой запуск tsx CLI = один node-процесс.
       */
      script: path.join(root, 'node_modules/tsx/dist/cli.mjs'),
      args: 'scripts-tmp/dashboard-server.ts',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      kill_timeout: 10000,
      merge_logs: true,
      time: true,
      env: {
        HOST: '0.0.0.0',
        PORT: '3008',
        /** Должен совпадать с `isOrganizerPaperStorePath` в dashboard-server (имя `organizer-paper.jsonl`). */
        STORE_PATH: path.join(root, 'data/paper2/organizer-paper.jsonl'),
        PAPER2_DIR: path.join(root, 'data/paper2'),
        DASHBOARD_LIVE_OSCAR_JSONL: path.join(root, 'data/live/pt1-oscar-live.jsonl'),
        DASHBOARD_LIVE_OSCAR_RISKY_JSONL: path.join(root, 'data/live/pt1-oscar-live-risky.jsonl'),
        /** Вторая плитка «Wallet» в шапке `/papertrader2` — баланс risky-кошелька (RPC как у основного Wallet). */
        DASHBOARD_LIVE_OSCAR_RISKY_WALLET_PUBKEY: 'HoFKBH9novJha1rzkHTBRqPrMbXtRNQL3wgJUWqfmp19',
        DASHBOARD_PAPER_OSCAR_V21_JSONL: path.join(root, 'data/paper2/paper-oscar-v21.jsonl'),
        DASHBOARD_PAPER_OSCAR_V22_JSONL: path.join(root, 'data/paper2/paper-oscar-v22.jsonl'),
        DASHBOARD_PAPER_OSCAR_RISKY_JSONL: path.join(root, 'data/paper2/paper-oscar-risky.jsonl'),
        /**
         * QuickNode Admin API → Telegram:
         * - `QUICKNODE_HOURLY_REMAINING_TELEGRAM=1` — не чаще 1×/ч `[ALERT][quicknode-balance]` (интервал ≥1h в коде + cooldown ниже).
         * - `QUICKNODE_USAGE_TELEGRAM` (общая дневная сводка) и milestones — выкл., чтобы не шумели.
         */
        QUICKNODE_USAGE_TELEGRAM: '0',
        QUICKNODE_HOURLY_REMAINING_TELEGRAM: '1',
        QUICKNODE_HOURLY_REMAINING_TELEGRAM_MS: '3600000',
        QUICKNODE_HOURLY_RECENT_MINUTES_LIST: '10,30,60',
        /** В конец `[ALERT][quicknode-balance]` — метрики discovery за окно из `data/live-discovery-health.json` (live-oscar). */
        QUICKNODE_HOURLY_APPEND_OSCAR_HEALTH: '1',
        QUICKNODE_BILLING_MILESTONES: '0',
        /** Дублирующая страховка в sender: один и тот же subtag не чаще 1 ч даже при двух процессах / перезапусках. */
        TELEGRAM_COOLDOWN_ALERT_QUICKNODE_BALANCE_MS: '3600000',
      },
    },
    {
      name: 'sa-raydium',
      cwd: root,
      script: 'scripts-tmp/raydium-collector.mjs',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      max_memory_restart: '300M',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        LIVE_TRADES_PATH: path.join(root, 'data/live/pt1-oscar-live.jsonl'),
      },
    },
    {
      name: 'sa-meteora',
      cwd: root,
      script: 'scripts-tmp/meteora-collector.mjs',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      max_memory_restart: '300M',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        LIVE_TRADES_PATH: path.join(root, 'data/live/pt1-oscar-live.jsonl'),
      },
    },
    {
      name: 'sa-orca',
      cwd: root,
      script: 'scripts-tmp/orca-collector.mjs',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      max_memory_restart: '300M',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        /** Explicit 60s — PM2 may retain removed keys across reload; override stale dump. */
        ORCA_COLLECTOR_INTERVAL_MS: '60000',
        LIVE_TRADES_PATH: path.join(root, 'data/live/pt1-oscar-live.jsonl'),
      },
    },
    {
      name: 'sa-moonshot',
      cwd: root,
      script: 'scripts-tmp/moonshot-collector.mjs',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      max_memory_restart: '300M',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        MOONSHOT_COLLECTOR_INTERVAL_MS: '60000',
        LIVE_TRADES_PATH: path.join(root, 'data/live/pt1-oscar-live.jsonl'),
      },
    },
    {
      name: 'sa-pumpswap',
      cwd: root,
      script: 'scripts-tmp/pumpswap-collector.mjs',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      max_memory_restart: '300M',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        LIVE_TRADES_PATH: path.join(root, 'data/live/pt1-oscar-live.jsonl'),
      },
    },
    {
      name: 'sa-wallet-orchestrator',
      cwd: root,
      script: 'scripts-tmp/sa-wallet-orchestrator.mjs',
      args: '--daemon',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 8000,
      max_memory_restart: '220M',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        /** W6.8 — Gecko multi-lane → QN → wallets; локальный потолок оркестратора см. SA_ORCH_MAX_QUICKNODE_CREDITS_PER_DAY. */
        SA_ORCH_SCHEDULER_TICK_MS: '10000',
        SA_ORCH_GECKO_TARGET_CALLS_PER_MINUTE: '24',
        /** W6.13 — detective ledger (orch/backfill/sigseed); глобальный кап выше суммы подпулов при низком фактическом расходе QN. */
        SA_QN_GLOBAL_CREDITS_PER_DAY: '4000000',
        SA_ORCH_MAX_QUICKNODE_CREDITS_PER_DAY: '2200000',
        SA_BACKFILL_MAX_CREDITS_PER_DAY: '500000',
        SA_ORCH_MAX_GECKO_HTTP_PER_DAY: '40000',
        SA_ORCH_MAX_RPC_PER_JOB: '1200',
        SA_ORCH_MAX_RPC_PER_POOL: '180',
        SA_ORCH_MAX_POOLS_PER_JOB: '20',
        SA_ORCH_SIG_PAGES_MAX: '4',
        SA_ORCH_MAX_TX_FETCHES_PER_POOL: '18',
        SA_ORCH_RPC_SLEEP_MS: '220',
      },
    },
    {
      name: 'sa-collector-watch',
      cwd: root,
      script: 'scripts-tmp/collector-log-watch.mjs',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      max_memory_restart: '120M',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        /** TELEGRAM_* из .env. Один чат: [ALERT][dex_collectors] — 429, тики, сеть, tick failed, fatal. */
        COLLECTOR_WATCH_POLL_MS: '15000',
        /** `0` — не слать dex_collectors в Telegram (логи PM2 остаются). */
        COLLECTOR_WATCH_TELEGRAM: '0',
      },
    },
    {
      name: 'sa-jupiter',
      cwd: root,
      script: 'scripts-tmp/jupiter-route-watcher.mjs',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      max_memory_restart: '350M',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        JUPITER_WATCHER_ENQUEUE_RPC: '0',
      },
    },
    {
      name: 'sa-direct-lp',
      cwd: root,
      script: 'scripts-tmp/direct-lp-detector.mjs',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      max_memory_restart: '300M',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        DIRECT_LP_ENQUEUE_RPC: '0',
      },
    },
    {
      name: 'live-oscar',
      cwd: root,
      /** Прямой `tsx` — один node-процесс под PM2 (как `live-oscar-dashboard`), без гонок `npm run` при reload. */
      script: path.join(root, 'node_modules/tsx/dist/cli.mjs'),
      args: 'src/scripts/live-oscar.ts',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      kill_timeout: 15000,
      max_memory_restart: '200M',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        /** Снимок для дашборда / QuickNode hourly (дефолт в коде тот же файл). */
        LIVE_DISCOVERY_HEALTH_SNAPSHOT_PATH: path.join(root, 'data/live-discovery-health.json'),
        /**
         * Paper-слой = паритет с `pt1-oscar` (W7.2 / holders / W7.6 / W7.4).
         * W7.3 priority fee, W7.5 liq-watch, W7.8 sim-audit — **только** этот процесс (на pt1-* выкл.).
         */
        PAPER_STRATEGY_KIND: 'dip',
        PAPER_STRATEGY_ID: 'live-oscar',
        /** Unused file — live-oscar never writes paper JSONL (P4-I1). */
        PAPER_TRADES_PATH: path.join(root, 'data/paper2/_live_oscar_unused_journal.jsonl'),
        PAPER_HEARTBEAT_INTERVAL_MS: '30000',
        PAPER_DISCOVERY_INTERVAL_MS: '10000',
        PAPER_TRACK_INTERVAL_MS: '30000',
        PAPER_FOLLOWUP_TICK_MS: '60000',
        PAPER_DRY_RUN: 'false',
        /** Staged-entry: полный нотионал **$1000**; первая нога **$400** на −7% от сигнала, вторая **$600** на −14%. */
        PAPER_POSITION_USD: '1000',
        PAPER_ENTRY_FIRST_LEG_FRACTION: '0.4',
        PAPER_LIVE_STAGED_ENTRY_ENABLED: '1',
        PAPER_LIVE_STAGED_ENTRY_FIRST_DROP_PCT: '7',
        PAPER_LIVE_STAGED_ENTRY_FIRST_LEG_USD: '400',
        PAPER_LIVE_STAGED_ENTRY_SECOND_DROP_PCT: '14',
        PAPER_LIVE_STAGED_ENTRY_SECOND_LEG_USD: '600',
        PAPER_LIVE_STAGED_ENTRY_KILL_DROP_PCT: '24',
        PAPER_LIVE_STAGED_ENTRY_SIGNAL_TTL_MS: '3600000',
        PAPER_SAFETY_CHECK_ENABLED: '1',
        PAPER_PRIORITY_FEE_ENABLED: '1',
        PAPER_PRIORITY_FEE_TICKER_MS: '60000',
        PAPER_PRIORITY_FEE_MAX_AGE_MS: '600000',
        PAPER_PRIORITY_FEE_RPC_TIMEOUT_MS: '2500',
        PAPER_PRIORITY_FEE_PERCENTILE: 'p75',
        PAPER_PRIORITY_FEE_TARGET_CU: '200000',
        PAPER_PRIORITY_FEE_CACHE_PATH: path.join(root, 'data/priority-fee-cache-live-oscar.json'),
        PAPER_LIVE_MCAP_TTL_MS: '30000',

        PAPER_ENABLE_LAUNCHPAD_LANE: 'false',
        PAPER_ENABLE_MIGRATION_LANE: 'false',
        PAPER_ENABLE_POST_LANE: 'true',
        /** Пост-lane: мин. возраст пула в снимке 36 ч (паритет четырёх Oscar-плиток); верхняя граница не задана. */
        PAPER_POST_MIN_AGE_MIN: '2160',
        PAPER_POST_MAX_AGE_MIN: '0',
        PAPER_POST_MIN_LIQ_USD: '140000',
        PAPER_POST_MIN_VOL_5M_USD: '10000',
        PAPER_POST_MIN_BUYS_5M: '4',
        PAPER_POST_MIN_SELLS_5M: '3',
        PAPER_POST_MIN_BS: '0.98',
        PAPER_VOL_5M_1H_GUARD_ENABLED: '1',
        PAPER_VOL_1H_MIN_USD: '36000',
        PAPER_VOL_5M_SPIKE_MAX_MULT: '7',
        PAPER_MIN_HOLDER_COUNT: '3000',

        PAPER_DIP_LOOKBACK_MIN: '120',
        PAPER_DIP_LOOKBACK_WINDOWS_MIN: '120,360,720',
        /** Live Oscar only: мин. глубина просадки цены от high выбранного окна (OR 120/360/720 мин). Значение −20 в env = −20%. */
        PAPER_DIP_MIN_DROP_PCT: '-20',
        PAPER_DIP_MAX_DROP_PCT: '-50',
        PAPER_DIP_MIN_IMPULSE_PCT: '12',
        PAPER_DIP_MIN_AGE_MIN: '0',
        PAPER_DIP_COOLDOWN_MIN: '30',
        PAPER_DIP_COOLDOWN_MIN_SCALP: '20',
        /** После **любого** полного закрытия по mint — 10m пауза повторного входа (имена env исторически `LOSS_`). */
        PAPER_DIP_LOSS_EXIT_COOLDOWN_ENABLED: 'true',
        PAPER_DIP_LOSS_EXIT_COOLDOWN_MINUTES: '10',
        PAPER_DIP_LOSS_EXIT_COOLDOWN_HOURS: '0',

        PAPER_DIP_RECOVERY_VETO_ENABLED: '1',
        PAPER_DIP_RECOVERY_VETO_WINDOWS_MIN: '30,60',
        PAPER_DIP_RECOVERY_VETO_MAX_BOUNCE_PCT: '12',

        /** Live: без tp-regime классов на входе; режимы A/B по IDEALIZED_OSCAR_STACK_SPEC §8.2–§9.2. */
        PAPER_TP_REGIME_ENABLED: '0',
        /** Режим A/B: A до усреднения по `PAPER_DCA_LEVELS` или до первого TP; B после DCA — держим B до закрытия; env `PAPER_LIVE_EXIT_MODE_B_*`. */
        PAPER_LIVE_EXIT_MODE_AB: '1',
        PAPER_LIVE_EXIT_MODE_B_TRAIL_DROP: '0.12',
        PAPER_LIVE_EXIT_MODE_B_TRAIL_TRIGGER_X: '1.06',
        PAPER_LIVE_EXIT_MODE_B_TIMEOUT_HOURS: '4',
        PAPER_LIVE_EXIT_MODE_B_DCA_KILLSTOP: '0',
        /**
         * Режим B: включается после staged-второй ноги; signal kill-stop −24%% от исходного сигнала.
         * Лестница TP: **+2.5%%** к средней за ступень, **5%%** остатка за ступень (`PAPER_LIVE_EXIT_MODE_B_TP_GRID_*`).
         * Верхний лимит ступеней не задаём — для **live-oscar** в режиме B `tpGridEffective` даёт бесконечную сетку.
         * Трейл **`ladder_retrace`** без изменений: при откате — к порогу предыдущей ступени.
         */
        PAPER_LIVE_EXIT_MODE_B_TP_GRID_STEP_PNL: '0.025',
        PAPER_LIVE_EXIT_MODE_B_TP_GRID_SELL_FRACTION: '0.05',
        PAPER_LIVE_EXIT_MODE_B_TP_GRID_FIRST_RUNG_RETRACE_MIN_PNL: '0.02',

        /**
         * Дополнительные DCA отключены: вторая staged-нога — единственное усреднение.
         * Старый 5-секундный `LIVE_ENTRY_SCALE_IN_*` для основного Live Oscar выключен ниже.
         */
        PAPER_DCA_LEVELS: '',
        /** Kill-stop для staged-entry считается отдельной signal-based логикой (`PAPER_LIVE_STAGED_ENTRY_KILL_DROP_PCT`). */
        PAPER_DCA_KILLSTOP: '0',
        /**
         * Режим A — «полная лестница»: **+2.5%%** к средней за ступень; **5%%** остатка за ступень;
         * retrace-защита после 1-й ступени (`PAPER_TP_GRID_FIRST_RUNG_RETRACE_MIN_PNL`).
         */
        PAPER_TP_LADDER: '',
        PAPER_TP_GRID_STEP_PNL: '0.025',
        PAPER_TP_GRID_SELL_FRACTION: '0.05',
        PAPER_TP_GRID_FIRST_RUNG_RETRACE_MIN_PNL: '0.025',
        PAPER_TP_X: '100',
        PAPER_SL_X: '0',
        PAPER_TRAIL_MODE: 'ladder_retrace',
        PAPER_TRAIL_DROP: '0.10',
        PAPER_TRAIL_TRIGGER_X: '1.10',
        /** Live Oscar — тайм-аут 8 ч; в трекере отключён после первого partial TP или DCA (см. tracker `timeoutSuppressedByProgress`). */
        PAPER_TIMEOUT_HOURS: '8',
        PAPER_PEAK_LOG_STEP_PCT: '1',

        PAPER_DIP_WHALE_ANALYSIS_ENABLED: '1',
        PAPER_DIP_REQUIRE_WHALE_TRIGGER: '0',
        PAPER_DIP_LARGE_SELL_USD: '3000',
        PAPER_DIP_RECENT_LOOKBACK_MIN: '10',
        PAPER_DIP_CAPITULATION_PCT: '0.7',
        PAPER_DIP_WHALE_SILENCE_MIN: '10',
        PAPER_DIP_GROUP_SELL_USD: '5000',
        PAPER_DIP_GROUP_MIN_SELLERS: '2',
        PAPER_DIP_GROUP_DUMP_PCT: '0.4',
        PAPER_DIP_BLOCK_CREATOR_DUMP: '1',
        PAPER_DIP_CREATOR_DUMP_LOOKBACK_MIN: '20',
        PAPER_DIP_CREATOR_DUMP_MIN_PCT: '0.05',
        PAPER_DIP_CREATOR_DUMP_MAX_PCT: '0.6',
        PAPER_DIP_DCA_PRED_MIN_SELLS_24H: '4',
        PAPER_DIP_DCA_PRED_MIN_INTERVAL_MIN: '30',
        PAPER_DIP_DCA_PRED_MIN_CHUNK_USD: '3000',
        PAPER_DIP_DCA_AGGR_MIN_SELLS_24H: '6',
        PAPER_DIP_DCA_AGGR_MAX_INTERVAL_MIN: '15',

        /** Off: live GPA/addon holders (W7.6) не используются — порог по `holder_count` из SQL-снимка коллекторов (`globalGate`). */
        PAPER_HOLDERS_LIVE_ENABLED: '0',
        PAPER_HOLDERS_USE_QN_ADDON: '0',
        PAPER_HOLDERS_TTL_MS: '90000',
        PAPER_HOLDERS_NEG_TTL_MS: '15000',
        PAPER_HOLDERS_MAX_PER_TICK: '10',
        PAPER_HOLDERS_TIMEOUT_MS: '4000',
        PAPER_HOLDERS_INCLUDE_TOKEN2022: '1',
        PAPER_HOLDERS_ON_FAIL: 'db_fallback',
        PAPER_HOLDERS_DB_WRITEBACK: '1',
        /** Прогрев `tokens.holder_count` для до N кандидатов с нулём в SQL до основного eval (см. dip-clones). */
        PAPER_HOLDERS_SNAPSHOT_WARMUP_MAX: '12',
        PAPER_HOLDERS_GPA_CREDITS_PER_CALL: '100',
        QN_FEATURE_BUDGET_HOLDERS: '10000000',

        PAPER_PRICE_VERIFY_ENABLED: '1',
        PAPER_PRICE_VERIFY_BLOCK_ON_FAIL: '1',
        PAPER_PRICE_VERIFY_USE_JUPITER_PRICE: '0',
        PAPER_PRICE_VERIFY_MAX_SLIP_PCT: '4.0',
        PAPER_PRICE_VERIFY_MAX_SLIP_BPS: '400',
        PAPER_PRICE_VERIFY_MAX_PRICE_IMPACT_PCT: '8.0',
        PAPER_PRICE_VERIFY_TIMEOUT_MS: '2500',
        PAPER_PRICE_VERIFY_EXIT_ENABLED: '1',
        PAPER_PRICE_VERIFY_EXIT_BLOCK_ON_FAIL: '1',
        /** После N defer pre-exit Jupiter verify по TIMEOUT — один проход без block_on_fail (см. live_exit_verify_defer). */
        PAPER_PRICE_VERIFY_EXIT_MAX_DEFERS_ESCALATION: '60',

        PAPER_SIM_AUDIT_ENABLED: '1',
        PAPER_SIM_SAMPLE_PCT: '5',
        PAPER_SIM_MAX_WALL_MS: '8000',
        PAPER_SIM_BUILD_TIMEOUT_MS: '5000',
        PAPER_SIM_USE_JUPITER_BUILD: '1',
        PAPER_SIM_CREDS_PER_CALL: '30',
        PAPER_SIM_STRICT_BUDGET: '1',

        PAPER_IMPULSE_CONFIRM_ENABLED: '1',
        PAPER_IMPULSE_DIP_POLICY: 'parallel_and',
        PAPER_IMPULSE_PG_MIN_DROP_PCT: '12',
        PAPER_IMPULSE_RPC_MAX_PER_MIN: '30',
        QN_FEATURE_BUDGET_IMPULSE_CONFIRM: '5000000',
        IMPULSE_QN_ROLLING_MAX_CREDITS: '1000000',

        PAPER_LIQ_WATCH_ENABLED: '1',
        PAPER_LIQ_WATCH_FORCE_CLOSE: '1',
        PAPER_LIQ_WATCH_DRAIN_PCT: '35',
        PAPER_LIQ_WATCH_MIN_AGE_MIN: '1',
        PAPER_LIQ_WATCH_CONSECUTIVE_FAILURES: '2',
        PAPER_LIQ_WATCH_SNAPSHOT_MAX_AGE_MS: '120000',
        PAPER_LIQ_WATCH_RPC_FALLBACK: '0',
        PAPER_LIQ_WATCH_STAMP_ON_ALL_CLOSE: '1',
        PAPER_LIQ_WATCH_STAMP_ON_TRACK: '0',

        /** W8.0 §9 rollout — шаг 3: `live` + микролимиты §3.3 (sendTransaction + confirm); см. RUNBOOK §0.2 и [`W8.0_live_oscar_trading_bot.md`](docs/strategy/specs/W8.0_live_oscar_trading_bot.md) §9. */
        LIVE_STRATEGY_ENABLED: '1',
        LIVE_EXECUTION_MODE: 'live',
        LIVE_STRATEGY_PROFILE: 'oscar',
        LIVE_STRATEGY_ID: 'live-oscar',
        LIVE_TRADES_PATH: path.join(root, 'data/live/pt1-oscar-live.jsonl'),
        /** `live_discovery_eval` / `live_discovery_skip_open` в JSONL (отключить: `0`). */
        LIVE_DISCOVERY_AUDIT_JSONL: '1',
        /** Полный аудит по mint из whitelist-файла: pass/fail eval, `universe_miss`, `tick_skip`. */
        LIVE_DISCOVERY_DEEP_AUDIT_JSONL: '1',
        LIVE_DISCOVERY_DEEP_AUDIT_WHITELIST_PATH: path.join(root, 'data/live/live-oscar-mint-whitelist.txt'),
        /** Минимальный интервал (мс) между повторными `universe_miss` / `tick_skip` по одному mint. */
        LIVE_DISCOVERY_DEEP_AUDIT_UNIVERSE_MISS_MIN_MS: '60000',
        /** Разрешённые mint для новых входов; иначе skip + Telegram (см. `LIVE_MINT_WHITELIST_TELEGRAM_CATEGORY`). */
        LIVE_MINT_WHITELIST_ENABLED: '1',
        LIVE_MINT_WHITELIST_PATH: path.join(root, 'data/live/live-oscar-mint-whitelist.txt'),
        /** `ADVICE` — не ALERT (тише: учитываются тихие часы `TELEGRAM_QUIET_*`). При желании: `ALERT`. */
        LIVE_MINT_WHITELIST_TELEGRAM_CATEGORY: 'ADVICE',
        /** `0` — каждый новый проход гейтов снова шлёт TG по этому mint (без кулдауна). */
        LIVE_MINT_WHITELIST_NOTIFY_COOLDOWN_MS: '0',
        /** Ручной blacklist mint — до dip/Jupiter и без открытия позиций (файл в репозитории). */
        LIVE_MINT_BLACKLIST_ENABLED: '1',
        LIVE_MINT_BLACKLIST_PATH: path.join(root, 'data/live/live-oscar-mint-blacklist.txt'),
        /**
         * Отдельный бот для TG только по `live_whitelist_miss` и `live_whitelist_consec_loss_drop`.
         * Эти алерты всегда без тихих часов (`skipQuietHours` в коде).
         */
        LIVE_MINT_WHITELIST_TELEGRAM_BOT_TOKEN: '8617384935:AAEjPboG6mfzcZd_DXS5o6bUXrQicZZEz30',
        LIVE_MINT_WHITELIST_TELEGRAM_CHAT_ID: '-1003878024799',
        /** После N подряд убыточных полных закрытий по mint — удаление из whitelist + Telegram (`mint-whitelist.ts`). `0` = выкл. */
        LIVE_MINT_WHITELIST_REMOVE_AFTER_CONSEC_LOSSES: '2',
        /**
         * Shadow diagnostics — только JSONL (+ блок в hourly-report); не меняет решения по сделкам.
         * Jupiter/RPC нагрузка растёт при SAMPLE_PCT=100; при лимитах снизить SAMPLE_PCT или выставить ALT-доли в 0.
         */
        SIGNAL_LAB_ENABLED: '1',
        SIGNAL_LAB_SAMPLE_PCT: '100',
        SIGNAL_LAB_PATH: path.join(root, 'data/live/signal-lab.jsonl'),
        SIGNAL_LAB_ALT_PROBE_FRACTION: '0.55',
        MTM_SHADOW_ENABLED: '1',
        MTM_SHADOW_SAMPLE_PCT: '100',
        MTM_SHADOW_PATH: path.join(root, 'data/live/mtm-shadow.jsonl'),
        MTM_SHADOW_ALT_FRACTION: '0.58',
        /** Live JSONL + `[HEALTH][live_oscar_pulse]` Telegram (uses `TELEGRAM_BOT_TOKEN` / `TELEGRAM_CHAT_ID`). Отключить TG: `LIVE_TELEGRAM_HEARTBEAT=0`. */
        LIVE_HEARTBEAT_INTERVAL_MS: '1800000',
        /** Файл keypair торгового кошелька на VPS (`chmod 600`). После замены файла задайте LIVE_WALLET_PUBKEY (совпадает с проверкой в коде). */
        LIVE_WALLET_SECRET: path.join(root, 'data/live/live-oscar-micro.keypair.json'),
        LIVE_WALLET_PUBKEY: '2sSu7dSwux8sKUYEgDtchx679YzuWG6Sbq54Db8vzswc',
        LIVE_SIM_ENABLED: '1',
        LIVE_SIM_TIMEOUT_MS: '12000',
        LIVE_SIM_CREDITS_PER_CALL: '30',
        /** W8.0 §10 — max Jupiter quote age (ms) before sign/send; `0` = disable (see `loadLiveOscarConfig`). */
        LIVE_QUOTE_MAX_AGE_MS: '8000',
        /**
         * `0` — не слать `live-jupiter-tracker-diverge` / `live-jupiter-tracker-fallback` в Telegram.
         * Circuit breaker price-verify: `JUPITER_QUOTE_CIRCUIT_TELEGRAM=0` при необходимости отдельно.
         */
        LIVE_JUPITER_TRACKER_TELEGRAM: '0',
        /** Jupiter quote + swap: max execution tolerances (bps). */
        LIVE_DEFAULT_SLIPPAGE_BPS: '300',
        /**
         * Jupiter `/swap/v1/swap`: cap priority fee at **0.0001 SOL** (100_000 lamports) via `priorityLevelWithMaxLamports`.
         * Optional override: `LIVE_JUPITER_SWAP_PRIORITY_LEVEL` = medium | high | veryHigh (default medium).
         */
        LIVE_JUPITER_PRIORITY_MAX_SOL: '0.0001',
        /** Полный нотионал (= `PAPER_POSITION_USD`); SOL на swap — из Jupiter quote по USD-нотации ноги. */
        LIVE_MAX_POSITION_USD: '1000',
        LIVE_MAX_OPEN_POSITIONS: '30',
        /**
         * Phase 5: гейт «свободный SOL ≥ k·X» + capital_skip / CAPITAL_ROTATE — выкл.
         * (Оценка free SOL через getBalance расходилась с реальностью; swap и так использует кошелёк.)
         * Включить прежнее W8.0-p5: LIVE_PHASE5_FREE_SOL_GATE_ENABLED=1 (опц. LIVE_CAPITAL_ROTATE_ENABLED=1).
         */
        LIVE_PHASE5_FREE_SOL_GATE_ENABLED: '0',
        LIVE_KILL_AFTER_CONSEC_FAIL: '3',
        /**
         * Гейты по оценке нативного SOL через getBalance — выкл. (пустая строка ⇒ в коде порог не задаётся).
         * Перекрывает возможные значения из `/opt/solana-alpha/.env` для PM2-процесса.
         */
        LIVE_MIN_WALLET_SOL: '',
        LIVE_MIN_WALLET_SOL_EQUITY_USD: '',
        /** Live-only: не открывать новые позиции при «просадке» BTC (Binance 1h/4h); `0` = выкл. см. `LIVE_BTC_GATE_ENABLED`. */
        LIVE_BTC_GATE_ENABLED: '1',
        /** 0 = выкл. Иначе снять exposure block (parity) после N мс — см. `LIVE_RECONCILE_BLOCK_MAX_MS` в config. */
        LIVE_RECONCILE_BLOCK_MAX_MS: '0',
        /** Live `buy_open`: не покупать mint, если на кошельке уже ≥ этой оценки USD (баланс × цена). 0 = выкл. */
        LIVE_SKIP_BUY_OPEN_WALLET_MINT_MIN_USD: '30',
        /** После `live_position_close`: через N мс дожать остаток mint на кошельке (`sell_full`). 0 = выкл. */
        LIVE_POST_CLOSE_TAIL_SWEEP_DELAY_MS: '60000',

        /** Старый 5-секундный scale-in отключён: staged-entry исполняет вторую ногу по −14% от сигнала. */
        LIVE_ENTRY_SCALE_IN_ENABLED: '0',
        /** Legacy-настройки оставлены только для risky/бумажных профилей и не активны при LIVE_ENTRY_SCALE_IN_ENABLED=0. */
        LIVE_ENTRY_SCALE_IN_DELAY_MS: '5000',
        /** Коридор второй ноги к якорю первой ноги: до +1% / до −2%; вне коридора — пауза `LIVE_ENTRY_SCALE_IN_OUT_OF_CORRIDOR_POLL_MS`. */
        LIVE_ENTRY_SCALE_IN_CORRIDOR_UP_PCT: '1',
        LIVE_ENTRY_SCALE_IN_CORRIDOR_DOWN_PCT: '2',
        LIVE_ENTRY_SCALE_IN_OUT_OF_CORRIDOR_POLL_MS: '30000',
        LIVE_ENTRY_SCALE_IN_MAX_SWAP_ATTEMPTS: '8',
        LIVE_ENTRY_SCALE_IN_RETRY_BACKOFF_MS: '2000',

        /** Периодический хвост на кошельке + force-close зависших open (`src/live/periodic-self-heal.ts`). */
        LIVE_PERIODIC_SELF_HEAL_MS: '1800000',
        LIVE_PERIODIC_SWEEP_MIN_USD: '0.25',
        LIVE_PERIODIC_STUCK_GRACE_HOURS: '0.5',
        /** `1` = продавать любые SPL не в open выше min USD (осторожно: скам-airdrops). */
        LIVE_PERIODIC_SWEEP_UNKNOWN_CHAIN_ONLY: '0',
      },
    },
    /**
     * Live Oscar Risky — тот же код и live-исполнение, что **live-oscar**; мягкие входы; без верхних капов по liq/vol/holders; нотионал **$200** (ноги **$150+$50**, DCA −3% ещё **$40**).
     * Блок **live-oscar** выше не трогать. Ключ: `data/live/live-oscar-risky.keypair.json` (gitignore); **`LIVE_WALLET_PUBKEY`** в env процесса.
     */
    {
      name: 'live-oscar-risky',
      cwd: root,
      script: path.join(root, 'node_modules/tsx/dist/cli.mjs'),
      args: 'src/scripts/live-oscar.ts',
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      kill_timeout: 15000,
      max_memory_restart: '200M',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        /** Отдельно от основного live-oscar — иначе оба процесса перезаписывают один JSON. */
        LIVE_DISCOVERY_HEALTH_SNAPSHOT_PATH: path.join(root, 'data/live-discovery-health-live-oscar-risky.json'),
        PAPER_STRATEGY_KIND: 'dip',
        PAPER_STRATEGY_ID: 'live-oscar-risky',
        PAPER_TRADES_PATH: path.join(root, 'data/paper2/_live_oscar_risky_unused_journal.jsonl'),
        PAPER_HEARTBEAT_INTERVAL_MS: '30000',
        PAPER_DISCOVERY_INTERVAL_MS: '10000',
        PAPER_TRACK_INTERVAL_MS: '30000',
        PAPER_FOLLOWUP_TICK_MS: '60000',
        PAPER_DRY_RUN: 'false',
        /** $200 total: первая нога $150, вторая $50 (scale-in). DCA −3%: доля от `PAPER_POSITION_USD` → **$40** при `-3:0.2`. */
        PAPER_POSITION_USD: '200',
        PAPER_ENTRY_FIRST_LEG_FRACTION: '0.75',
        PAPER_SAFETY_CHECK_ENABLED: '1',
        PAPER_PRIORITY_FEE_ENABLED: '1',
        PAPER_PRIORITY_FEE_TICKER_MS: '60000',
        PAPER_PRIORITY_FEE_MAX_AGE_MS: '600000',
        PAPER_PRIORITY_FEE_RPC_TIMEOUT_MS: '2500',
        PAPER_PRIORITY_FEE_PERCENTILE: 'p75',
        PAPER_PRIORITY_FEE_TARGET_CU: '200000',
        PAPER_PRIORITY_FEE_CACHE_PATH: path.join(root, 'data/priority-fee-cache-live-oscar-risky.json'),
        PAPER_LIVE_MCAP_TTL_MS: '30000',
        PAPER_ENABLE_LAUNCHPAD_LANE: 'false',
        PAPER_ENABLE_MIGRATION_LANE: 'false',
        PAPER_ENABLE_POST_LANE: 'true',
        /** Мягче live-oscar: как paper-oscar-risky — мин. возраст пула в снимке 6 ч. */
        PAPER_POST_MIN_AGE_MIN: '360',
        PAPER_POST_MAX_AGE_MIN: '0',
        /** POST min liq как у `paper-oscar-risky`; верхний порог по liq явно выключен. */
        PAPER_POST_MIN_LIQ_USD: '100000',
        PAPER_POST_MAX_LIQ_USD: '0',
        PAPER_POST_MIN_VOL_5M_USD: '3000',
        /** Верхний порог по vol5m/vol1h явно выключен — только min + spike-guard (как у paper-oscar-risky по объёмам). */
        PAPER_POST_MIN_BUYS_5M: '4',
        PAPER_POST_MIN_SELLS_5M: '3',
        PAPER_POST_MIN_BS: '0.98',
        PAPER_VOL_5M_1H_GUARD_ENABLED: '1',
        PAPER_VOL_1H_MIN_USD: '20000',
        /** Явный `0`: переопределяет возможный `PAPER_VOL_*_MAX_*` из общего `.env` на хосте (иначе снова появляется vol1h>35999 в журнале). */
        PAPER_VOL_1H_MAX_USD: '0',
        PAPER_POST_MAX_VOL_5M_USD: '0',
        PAPER_VOL_5M_SPIKE_MAX_MULT: '7',
        PAPER_MIN_HOLDER_COUNT: '1000',
        /** Верхний cap по holders выключен; оставляем только нижний порог. */
        PAPER_GLOBAL_MAX_HOLDER_COUNT: '0',
        /** Risky-only: сигнал входа держим 10 мин; вход только если цена в диапазоне [-20%, +3%] от цены сигнала. */
        PAPER_ENTRY_RECHECK_DELAY_MS: '600000',
        PAPER_ENTRY_RECHECK_MIN_CHANGE_PCT: '-20',
        PAPER_ENTRY_RECHECK_MAX_CHANGE_PCT: '3',
        PAPER_DIP_LOOKBACK_MIN: '120',
        PAPER_DIP_LOOKBACK_WINDOWS_MIN: '120,360,720',
        PAPER_DIP_MIN_DROP_PCT: '-20',
        PAPER_DIP_MAX_DROP_PCT: '-50',
        PAPER_DIP_MIN_IMPULSE_PCT: '12',
        PAPER_DIP_MIN_AGE_MIN: '0',
        PAPER_DIP_COOLDOWN_MIN: '30',
        PAPER_DIP_COOLDOWN_MIN_SCALP: '20',
        PAPER_DIP_LOSS_EXIT_COOLDOWN_ENABLED: 'true',
        PAPER_DIP_LOSS_EXIT_COOLDOWN_MINUTES: '10',
        PAPER_DIP_LOSS_EXIT_COOLDOWN_HOURS: '0',
        PAPER_DIP_RECOVERY_VETO_ENABLED: '1',
        PAPER_DIP_RECOVERY_VETO_WINDOWS_MIN: '30,60',
        PAPER_DIP_RECOVERY_VETO_MAX_BOUNCE_PCT: '12',
        PAPER_TP_REGIME_ENABLED: '0',
        PAPER_LIVE_EXIT_MODE_AB: '1',
        PAPER_LIVE_EXIT_MODE_B_TRAIL_DROP: '0.12',
        PAPER_LIVE_EXIT_MODE_B_TRAIL_TRIGGER_X: '1.06',
        PAPER_LIVE_EXIT_MODE_B_TIMEOUT_HOURS: '4',
        PAPER_LIVE_EXIT_MODE_B_DCA_KILLSTOP: '-0.16',
        PAPER_LIVE_EXIT_MODE_B_TP_GRID_STEP_PNL: '0.025',
        PAPER_LIVE_EXIT_MODE_B_TP_GRID_SELL_FRACTION: '0.05',
        PAPER_LIVE_EXIT_MODE_B_TP_GRID_FIRST_RUNG_RETRACE_MIN_PNL: '0.02',
        PAPER_DCA_LEVELS: '-3:0.2',
        PAPER_DCA_KILLSTOP: '-0.16',
        PAPER_TP_LADDER: '',
        PAPER_TP_GRID_STEP_PNL: '0.025',
        PAPER_TP_GRID_SELL_FRACTION: '0.05',
        PAPER_TP_GRID_FIRST_RUNG_RETRACE_MIN_PNL: '0.025',
        PAPER_TP_X: '100',
        PAPER_SL_X: '0',
        PAPER_TRAIL_MODE: 'ladder_retrace',
        PAPER_TRAIL_DROP: '0.10',
        PAPER_TRAIL_TRIGGER_X: '1.10',
        PAPER_TIMEOUT_HOURS: '8',
        PAPER_PEAK_LOG_STEP_PCT: '1',
        PAPER_DIP_WHALE_ANALYSIS_ENABLED: '1',
        PAPER_DIP_REQUIRE_WHALE_TRIGGER: '0',
        PAPER_DIP_LARGE_SELL_USD: '3000',
        PAPER_DIP_RECENT_LOOKBACK_MIN: '10',
        PAPER_DIP_CAPITULATION_PCT: '0.7',
        PAPER_DIP_WHALE_SILENCE_MIN: '10',
        PAPER_DIP_GROUP_SELL_USD: '5000',
        PAPER_DIP_GROUP_MIN_SELLERS: '2',
        PAPER_DIP_GROUP_DUMP_PCT: '0.4',
        PAPER_DIP_BLOCK_CREATOR_DUMP: '1',
        PAPER_DIP_CREATOR_DUMP_LOOKBACK_MIN: '20',
        PAPER_DIP_CREATOR_DUMP_MIN_PCT: '0.05',
        PAPER_DIP_CREATOR_DUMP_MAX_PCT: '0.6',
        PAPER_DIP_DCA_PRED_MIN_SELLS_24H: '4',
        PAPER_DIP_DCA_PRED_MIN_INTERVAL_MIN: '30',
        PAPER_DIP_DCA_PRED_MIN_CHUNK_USD: '3000',
        PAPER_DIP_DCA_AGGR_MIN_SELLS_24H: '6',
        PAPER_DIP_DCA_AGGR_MAX_INTERVAL_MIN: '15',
        PAPER_HOLDERS_LIVE_ENABLED: '0',
        PAPER_HOLDERS_USE_QN_ADDON: '0',
        PAPER_HOLDERS_TTL_MS: '90000',
        PAPER_HOLDERS_NEG_TTL_MS: '15000',
        PAPER_HOLDERS_MAX_PER_TICK: '10',
        PAPER_HOLDERS_TIMEOUT_MS: '4000',
        PAPER_HOLDERS_INCLUDE_TOKEN2022: '1',
        PAPER_HOLDERS_ON_FAIL: 'db_fallback',
        PAPER_HOLDERS_DB_WRITEBACK: '1',
        PAPER_HOLDERS_SNAPSHOT_WARMUP_MAX: '12',
        PAPER_HOLDERS_GPA_CREDITS_PER_CALL: '100',
        QN_FEATURE_BUDGET_HOLDERS: '10000000',
        PAPER_PRICE_VERIFY_ENABLED: '1',
        PAPER_PRICE_VERIFY_BLOCK_ON_FAIL: '1',
        PAPER_PRICE_VERIFY_USE_JUPITER_PRICE: '0',
        PAPER_PRICE_VERIFY_MAX_SLIP_PCT: '4.0',
        PAPER_PRICE_VERIFY_MAX_SLIP_BPS: '400',
        PAPER_PRICE_VERIFY_MAX_PRICE_IMPACT_PCT: '8.0',
        PAPER_PRICE_VERIFY_TIMEOUT_MS: '2500',
        PAPER_PRICE_VERIFY_EXIT_ENABLED: '1',
        PAPER_PRICE_VERIFY_EXIT_BLOCK_ON_FAIL: '1',
        PAPER_PRICE_VERIFY_EXIT_MAX_DEFERS_ESCALATION: '60',
        PAPER_SIM_AUDIT_ENABLED: '1',
        PAPER_SIM_SAMPLE_PCT: '5',
        PAPER_SIM_MAX_WALL_MS: '8000',
        PAPER_SIM_BUILD_TIMEOUT_MS: '5000',
        PAPER_SIM_USE_JUPITER_BUILD: '1',
        PAPER_SIM_CREDS_PER_CALL: '30',
        PAPER_SIM_STRICT_BUDGET: '1',
        PAPER_IMPULSE_CONFIRM_ENABLED: '1',
        PAPER_IMPULSE_DIP_POLICY: 'parallel_and',
        PAPER_IMPULSE_PG_MIN_DROP_PCT: '12',
        PAPER_IMPULSE_RPC_MAX_PER_MIN: '30',
        QN_FEATURE_BUDGET_IMPULSE_CONFIRM: '5000000',
        IMPULSE_QN_ROLLING_MAX_CREDITS: '1000000',
        PAPER_LIQ_WATCH_ENABLED: '1',
        PAPER_LIQ_WATCH_FORCE_CLOSE: '1',
        PAPER_LIQ_WATCH_DRAIN_PCT: '35',
        PAPER_LIQ_WATCH_MIN_AGE_MIN: '1',
        PAPER_LIQ_WATCH_CONSECUTIVE_FAILURES: '2',
        PAPER_LIQ_WATCH_SNAPSHOT_MAX_AGE_MS: '120000',
        PAPER_LIQ_WATCH_RPC_FALLBACK: '0',
        PAPER_LIQ_WATCH_STAMP_ON_ALL_CLOSE: '1',
        PAPER_LIQ_WATCH_STAMP_ON_TRACK: '0',
        /** Живая торговля risky Oscar (`0` — только наблюдение / replay-off). */
        LIVE_STRATEGY_ENABLED: '1',
        LIVE_EXECUTION_MODE: 'live',
        LIVE_STRATEGY_PROFILE: 'oscar',
        LIVE_STRATEGY_ID: 'live-oscar-risky',
        LIVE_TRADES_PATH: path.join(root, 'data/live/pt1-oscar-live-risky.jsonl'),
        LIVE_DISCOVERY_AUDIT_JSONL: '1',
        LIVE_DISCOVERY_DEEP_AUDIT_JSONL: '1',
        /** Нет allowlist: risky-слой ограничен нижними гейтами и risk-фильтрами; верхние cap по liq/vol/holders выключены. */
        LIVE_DISCOVERY_DEEP_AUDIT_UNIVERSE_MISS_MIN_MS: '60000',
        LIVE_MINT_WHITELIST_ENABLED: '0',
        LIVE_MINT_WHITELIST_PATH: path.join(root, 'data/live/live-oscar-risky-mint-whitelist.txt'),
        LIVE_MINT_WHITELIST_TELEGRAM_CATEGORY: 'ADVICE',
        LIVE_MINT_WHITELIST_NOTIFY_COOLDOWN_MS: '0',
        LIVE_MINT_BLACKLIST_ENABLED: '1',
        LIVE_MINT_BLACKLIST_PATH: path.join(root, 'data/live/live-oscar-risky-mint-blacklist.txt'),
        LIVE_MINT_WHITELIST_REMOVE_AFTER_CONSEC_LOSSES: '2',
        LIVE_OSCAR_PERMANENT_DENYLIST_LOCAL_PATH: path.join(root, 'data/live/live-oscar-risky-permanent-denylist.txt'),
        LIVE_OSCAR_PERMANENT_DENYLIST_SEED_PATH: path.join(root, 'data/live/live-oscar-permanent-denylist.seed.txt'),
        SIGNAL_LAB_ENABLED: '1',
        SIGNAL_LAB_SAMPLE_PCT: '100',
        SIGNAL_LAB_PATH: path.join(root, 'data/live/signal-lab-live-oscar-risky.jsonl'),
        SIGNAL_LAB_ALT_PROBE_FRACTION: '0.55',
        MTM_SHADOW_ENABLED: '1',
        MTM_SHADOW_SAMPLE_PCT: '100',
        MTM_SHADOW_PATH: path.join(root, 'data/live/mtm-shadow-live-oscar-risky.jsonl'),
        MTM_SHADOW_ALT_FRACTION: '0.58',
        LIVE_HEARTBEAT_INTERVAL_MS: '1800000',
        /** Торговый кошелёк risky (совпадает с `data/live/live-oscar-risky.keypair.json` на VPS). */
        LIVE_WALLET_PUBKEY: 'HoFKBH9novJha1rzkHTBRqPrMbXtRNQL3wgJUWqfmp19',
        LIVE_WALLET_SECRET: path.join(root, 'data/live/live-oscar-risky.keypair.json'),
        LIVE_SIM_ENABLED: '1',
        LIVE_SIM_TIMEOUT_MS: '12000',
        LIVE_SIM_CREDITS_PER_CALL: '30',
        LIVE_QUOTE_MAX_AGE_MS: '8000',
        LIVE_JUPITER_TRACKER_TELEGRAM: '0',
        LIVE_DEFAULT_SLIPPAGE_BPS: '300',
        LIVE_JUPITER_PRIORITY_MAX_SOL: '0.0001',
        LIVE_MAX_POSITION_USD: '200',
        LIVE_MAX_OPEN_POSITIONS: '30',
        LIVE_PHASE5_FREE_SOL_GATE_ENABLED: '0',
        LIVE_KILL_AFTER_CONSEC_FAIL: '3',
        LIVE_MIN_WALLET_SOL: '',
        LIVE_MIN_WALLET_SOL_EQUITY_USD: '',
        LIVE_BTC_GATE_ENABLED: '1',
        LIVE_RECONCILE_BLOCK_MAX_MS: '0',
        LIVE_SKIP_BUY_OPEN_WALLET_MINT_MIN_USD: '30',
        LIVE_POST_CLOSE_TAIL_SWEEP_DELAY_MS: '60000',
        LIVE_ENTRY_SCALE_IN_ENABLED: '1',
        LIVE_ENTRY_SCALE_IN_DELAY_MS: '5000',
        LIVE_ENTRY_SCALE_IN_CORRIDOR_UP_PCT: '1',
        LIVE_ENTRY_SCALE_IN_CORRIDOR_DOWN_PCT: '2',
        LIVE_ENTRY_SCALE_IN_OUT_OF_CORRIDOR_POLL_MS: '30000',
        LIVE_ENTRY_SCALE_IN_MAX_SWAP_ATTEMPTS: '8',
        LIVE_ENTRY_SCALE_IN_RETRY_BACKOFF_MS: '2000',
        LIVE_PERIODIC_SELF_HEAL_MS: '1800000',
        LIVE_PERIODIC_SWEEP_MIN_USD: '0.25',
        LIVE_PERIODIC_STUCK_GRACE_HOURS: '0.5',
        LIVE_PERIODIC_SWEEP_UNKNOWN_CHAIN_ONLY: '0',
        LIVE_TELEGRAM_HEARTBEAT: '0',
      },
    },
    /**
     * Paper Oscar Risky — бумага: тот же paper-слой, что у **live-oscar** (все `PAPER_*` ниже скопированы с процесса `live-oscar` в этом файле).
     * Затем смягчены только пост-gate пороги для эксперимента: vol 5m $3k, vol 1h guard $20k, мин. возраст пула 6 ч, holders ≥ 1k.
     * Живой Oscar в этом файле не менять.
     */
    {
      name: 'paper-oscar-risky',
      cwd: root,
      script: 'npm',
      args: 'run --silent paper-oscar-risky',
      interpreter: 'none',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      max_memory_restart: '200M',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        PAPER_STRATEGY_KIND: 'dip',
        PAPER_STRATEGY_ID: 'paper-oscar-risky',
        PAPER_TRADES_PATH: path.join(root, 'data/paper2/paper-oscar-risky.jsonl'),
        PAPER_HEARTBEAT_INTERVAL_MS: '30000',
        PAPER_DISCOVERY_INTERVAL_MS: '10000',
        PAPER_TRACK_INTERVAL_MS: '30000',
        PAPER_FOLLOWUP_TICK_MS: '60000',
        PAPER_DRY_RUN: 'false',
        PAPER_POSITION_USD: '600',
        PAPER_ENTRY_FIRST_LEG_FRACTION: '0.75',
        PAPER_SAFETY_CHECK_ENABLED: '1',
        PAPER_PRIORITY_FEE_ENABLED: '1',
        PAPER_PRIORITY_FEE_TICKER_MS: '60000',
        PAPER_PRIORITY_FEE_MAX_AGE_MS: '600000',
        PAPER_PRIORITY_FEE_RPC_TIMEOUT_MS: '2500',
        PAPER_PRIORITY_FEE_PERCENTILE: 'p75',
        PAPER_PRIORITY_FEE_TARGET_CU: '200000',
        PAPER_PRIORITY_FEE_CACHE_PATH: path.join(root, 'data/priority-fee-cache-paper-oscar-risky.json'),
        PAPER_LIVE_MCAP_TTL_MS: '30000',
        PAPER_ENABLE_LAUNCHPAD_LANE: 'false',
        PAPER_ENABLE_MIGRATION_LANE: 'false',
        PAPER_ENABLE_POST_LANE: 'true',
        /** Пост-lane (post_migration): смягчение min pool liq до $100k (live-oscar: $140k). */
        PAPER_POST_MIN_LIQ_USD: '100000',
        PAPER_POST_MAX_LIQ_USD: '0',
        PAPER_POST_MAX_AGE_MIN: '0',
        /** Смягчение: мин. возраст пула 6 ч (live: 36 ч). */
        PAPER_POST_MIN_AGE_MIN: '360',
        /** Смягчение: объём 5m (поле volume_5m в снимке), live: $10k. */
        PAPER_POST_MIN_VOL_5M_USD: '3000',
        PAPER_POST_MAX_VOL_5M_USD: '0',
        PAPER_POST_MIN_BUYS_5M: '4',
        PAPER_POST_MIN_SELLS_5M: '3',
        PAPER_POST_MIN_BS: '0.98',
        PAPER_VOL_5M_1H_GUARD_ENABLED: '1',
        /** Смягчение: нижний порог объёма за час (guard), live: $36k. */
        PAPER_VOL_1H_MIN_USD: '20000',
        PAPER_VOL_1H_MAX_USD: '0',
        PAPER_VOL_5M_SPIKE_MAX_MULT: '7',
        /** Смягчение: holders (live: 3000). */
        PAPER_MIN_HOLDER_COUNT: '1000',
        PAPER_GLOBAL_MAX_HOLDER_COUNT: '0',
        PAPER_DIP_LOOKBACK_MIN: '120',
        PAPER_DIP_LOOKBACK_WINDOWS_MIN: '120,360,720',
        PAPER_DIP_MIN_DROP_PCT: '-30',
        PAPER_DIP_MAX_DROP_PCT: '-50',
        PAPER_DIP_MIN_IMPULSE_PCT: '12',
        PAPER_DIP_MIN_AGE_MIN: '0',
        PAPER_DIP_COOLDOWN_MIN: '30',
        PAPER_DIP_COOLDOWN_MIN_SCALP: '20',
        PAPER_DIP_LOSS_EXIT_COOLDOWN_ENABLED: 'true',
        PAPER_DIP_LOSS_EXIT_COOLDOWN_MINUTES: '10',
        PAPER_DIP_LOSS_EXIT_COOLDOWN_HOURS: '0',
        PAPER_DIP_RECOVERY_VETO_ENABLED: '1',
        PAPER_DIP_RECOVERY_VETO_WINDOWS_MIN: '30,60',
        PAPER_DIP_RECOVERY_VETO_MAX_BOUNCE_PCT: '12',
        PAPER_TP_REGIME_ENABLED: '0',
        PAPER_LIVE_EXIT_MODE_AB: '1',
        PAPER_LIVE_EXIT_MODE_B_TRAIL_DROP: '0.12',
        PAPER_LIVE_EXIT_MODE_B_TRAIL_TRIGGER_X: '1.06',
        PAPER_LIVE_EXIT_MODE_B_TIMEOUT_HOURS: '4',
        PAPER_LIVE_EXIT_MODE_B_DCA_KILLSTOP: '-0.08',
        PAPER_LIVE_EXIT_MODE_B_TP_GRID_STEP_PNL: '0.025',
        PAPER_LIVE_EXIT_MODE_B_TP_GRID_SELL_FRACTION: '0.05',
        PAPER_LIVE_EXIT_MODE_B_TP_GRID_FIRST_RUNG_RETRACE_MIN_PNL: '0.02',
        PAPER_DCA_LEVELS: '-4:0.25',
        PAPER_DCA_KILLSTOP: '-0.08',
        PAPER_TP_LADDER: '',
        PAPER_TP_GRID_STEP_PNL: '0.025',
        PAPER_TP_GRID_SELL_FRACTION: '0.05',
        PAPER_TP_GRID_FIRST_RUNG_RETRACE_MIN_PNL: '0.025',
        PAPER_TP_X: '100',
        PAPER_SL_X: '0',
        PAPER_TRAIL_MODE: 'ladder_retrace',
        PAPER_TRAIL_DROP: '0.10',
        PAPER_TRAIL_TRIGGER_X: '1.10',
        PAPER_TIMEOUT_HOURS: '8',
        PAPER_PEAK_LOG_STEP_PCT: '1',
        PAPER_DIP_WHALE_ANALYSIS_ENABLED: '1',
        PAPER_DIP_REQUIRE_WHALE_TRIGGER: '0',
        PAPER_DIP_LARGE_SELL_USD: '3000',
        PAPER_DIP_RECENT_LOOKBACK_MIN: '10',
        PAPER_DIP_CAPITULATION_PCT: '0.7',
        PAPER_DIP_WHALE_SILENCE_MIN: '10',
        PAPER_DIP_GROUP_SELL_USD: '5000',
        PAPER_DIP_GROUP_MIN_SELLERS: '2',
        PAPER_DIP_GROUP_DUMP_PCT: '0.4',
        PAPER_DIP_BLOCK_CREATOR_DUMP: '1',
        PAPER_DIP_CREATOR_DUMP_LOOKBACK_MIN: '20',
        PAPER_DIP_CREATOR_DUMP_MIN_PCT: '0.05',
        PAPER_DIP_CREATOR_DUMP_MAX_PCT: '0.6',
        PAPER_DIP_DCA_PRED_MIN_SELLS_24H: '4',
        PAPER_DIP_DCA_PRED_MIN_INTERVAL_MIN: '30',
        PAPER_DIP_DCA_PRED_MIN_CHUNK_USD: '3000',
        PAPER_DIP_DCA_AGGR_MIN_SELLS_24H: '6',
        PAPER_DIP_DCA_AGGR_MAX_INTERVAL_MIN: '15',
        PAPER_HOLDERS_LIVE_ENABLED: '0',
        PAPER_HOLDERS_USE_QN_ADDON: '0',
        PAPER_HOLDERS_TTL_MS: '90000',
        PAPER_HOLDERS_NEG_TTL_MS: '15000',
        PAPER_HOLDERS_MAX_PER_TICK: '10',
        PAPER_HOLDERS_TIMEOUT_MS: '4000',
        PAPER_HOLDERS_INCLUDE_TOKEN2022: '1',
        PAPER_HOLDERS_ON_FAIL: 'db_fallback',
        PAPER_HOLDERS_DB_WRITEBACK: '1',
        PAPER_HOLDERS_SNAPSHOT_WARMUP_MAX: '12',
        PAPER_HOLDERS_GPA_CREDITS_PER_CALL: '100',
        QN_FEATURE_BUDGET_HOLDERS: '10000000',
        PAPER_PRICE_VERIFY_ENABLED: '1',
        PAPER_PRICE_VERIFY_BLOCK_ON_FAIL: '1',
        PAPER_PRICE_VERIFY_USE_JUPITER_PRICE: '0',
        PAPER_PRICE_VERIFY_MAX_SLIP_PCT: '4.0',
        PAPER_PRICE_VERIFY_MAX_SLIP_BPS: '400',
        PAPER_PRICE_VERIFY_MAX_PRICE_IMPACT_PCT: '8.0',
        PAPER_PRICE_VERIFY_TIMEOUT_MS: '2500',
        PAPER_PRICE_VERIFY_EXIT_ENABLED: '1',
        PAPER_PRICE_VERIFY_EXIT_BLOCK_ON_FAIL: '1',
        PAPER_PRICE_VERIFY_EXIT_MAX_DEFERS_ESCALATION: '60',
        PAPER_SIM_AUDIT_ENABLED: '1',
        PAPER_SIM_SAMPLE_PCT: '5',
        PAPER_SIM_MAX_WALL_MS: '8000',
        PAPER_SIM_BUILD_TIMEOUT_MS: '5000',
        PAPER_SIM_USE_JUPITER_BUILD: '1',
        PAPER_SIM_CREDS_PER_CALL: '30',
        PAPER_SIM_STRICT_BUDGET: '1',
        PAPER_IMPULSE_CONFIRM_ENABLED: '1',
        PAPER_IMPULSE_DIP_POLICY: 'parallel_and',
        PAPER_IMPULSE_PG_MIN_DROP_PCT: '12',
        PAPER_IMPULSE_RPC_MAX_PER_MIN: '30',
        QN_FEATURE_BUDGET_IMPULSE_CONFIRM: '5000000',
        IMPULSE_QN_ROLLING_MAX_CREDITS: '1000000',
        PAPER_LIQ_WATCH_ENABLED: '1',
        PAPER_LIQ_WATCH_FORCE_CLOSE: '1',
        PAPER_LIQ_WATCH_DRAIN_PCT: '35',
        PAPER_LIQ_WATCH_MIN_AGE_MIN: '1',
        PAPER_LIQ_WATCH_CONSECUTIVE_FAILURES: '2',
        PAPER_LIQ_WATCH_SNAPSHOT_MAX_AGE_MS: '120000',
        PAPER_LIQ_WATCH_RPC_FALLBACK: '0',
        PAPER_LIQ_WATCH_STAMP_ON_ALL_CLOSE: '1',
        PAPER_LIQ_WATCH_STAMP_ON_TRACK: '0',
        LIVE_ENTRY_SCALE_IN_ENABLED: '1',
        LIVE_ENTRY_SCALE_IN_DELAY_MS: '5000',
        LIVE_ENTRY_SCALE_IN_CORRIDOR_UP_PCT: '1',
        LIVE_ENTRY_SCALE_IN_CORRIDOR_DOWN_PCT: '2',
        LIVE_ENTRY_SCALE_IN_OUT_OF_CORRIDOR_POLL_MS: '30000',
        LIVE_ENTRY_SCALE_IN_MAX_SWAP_ATTEMPTS: '8',
        LIVE_ENTRY_SCALE_IN_RETRY_BACKOFF_MS: '2000',
      },
    },
    /**
     * Paper Oscar IDEALIZED V2.1 — те же гейты входа/данные, что live-oscar paper-слой; выходы по §1–§7 `IDEALIZED_OSCAR_STACK_SPEC_V2.md` v2.1.
     * Полный паритет `PAPER_*` с процессом **live-oscar** задаётся общим `.env` на хосте; здесь — отличия id/журнал/kill B/кэш priority fee + scale-in для второй ноги.
     */
    {
      name: 'paper-oscar-v21',
      cwd: root,
      script: 'npm',
      args: 'run --silent paper-oscar-v21',
      interpreter: 'none',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      max_memory_restart: '200M',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        PAPER_STRATEGY_KIND: 'dip',
        PAPER_STRATEGY_ID: 'paper-oscar-v21',
        PAPER_TRADES_PATH: path.join(root, 'data/paper2/paper-oscar-v21.jsonl'),
        PAPER_HEARTBEAT_INTERVAL_MS: '30000',
        PAPER_DISCOVERY_INTERVAL_MS: '10000',
        PAPER_TRACK_INTERVAL_MS: '30000',
        PAPER_FOLLOWUP_TICK_MS: '60000',
        PAPER_DRY_RUN: 'false',
        PAPER_POSITION_USD: '120',
        PAPER_ENTRY_FIRST_LEG_FRACTION: '0.75',
        PAPER_SAFETY_CHECK_ENABLED: '1',
        PAPER_PRIORITY_FEE_ENABLED: '1',
        PAPER_PRIORITY_FEE_TICKER_MS: '60000',
        PAPER_PRIORITY_FEE_MAX_AGE_MS: '600000',
        PAPER_PRIORITY_FEE_RPC_TIMEOUT_MS: '2500',
        PAPER_PRIORITY_FEE_PERCENTILE: 'p75',
        PAPER_PRIORITY_FEE_TARGET_CU: '200000',
        PAPER_PRIORITY_FEE_CACHE_PATH: path.join(root, 'data/priority-fee-cache-paper-oscar-v21.json'),
        PAPER_LIVE_MCAP_TTL_MS: '30000',
        PAPER_ENABLE_LAUNCHPAD_LANE: 'false',
        PAPER_ENABLE_MIGRATION_LANE: 'false',
        PAPER_ENABLE_POST_LANE: 'true',
        PAPER_POST_MIN_AGE_MIN: '2160',
        PAPER_POST_MAX_AGE_MIN: '0',
        PAPER_POST_MIN_LIQ_USD: '200000',
        PAPER_POST_MIN_VOL_5M_USD: '20000',
        PAPER_POST_MIN_BUYS_5M: '4',
        PAPER_POST_MIN_SELLS_5M: '3',
        PAPER_POST_MIN_BS: '0.98',
        PAPER_VOL_5M_1H_GUARD_ENABLED: '1',
        PAPER_VOL_1H_MIN_USD: '36000',
        PAPER_VOL_5M_SPIKE_MAX_MULT: '7',
        PAPER_MIN_HOLDER_COUNT: '3000',
        PAPER_DIP_LOOKBACK_MIN: '120',
        PAPER_DIP_LOOKBACK_WINDOWS_MIN: '120,360,720',
        PAPER_DIP_MIN_DROP_PCT: '-15',
        PAPER_DIP_MAX_DROP_PCT: '-50',
        PAPER_DIP_MIN_IMPULSE_PCT: '12',
        PAPER_DIP_MIN_AGE_MIN: '0',
        /** Бумага: без кулдауна entry→entry и без post-exit паузы. */
        PAPER_DIP_COOLDOWN_MIN: '0',
        PAPER_DIP_COOLDOWN_MIN_SCALP: '0',
        PAPER_DIP_LOSS_EXIT_COOLDOWN_ENABLED: 'false',
        PAPER_DIP_LOSS_EXIT_COOLDOWN_MINUTES: '0',
        PAPER_DIP_LOSS_EXIT_COOLDOWN_HOURS: '0',
        PAPER_DIP_RECOVERY_VETO_ENABLED: '1',
        PAPER_DIP_RECOVERY_VETO_WINDOWS_MIN: '30,60',
        PAPER_DIP_RECOVERY_VETO_MAX_BOUNCE_PCT: '12',
        PAPER_TP_REGIME_ENABLED: '0',
        PAPER_LIVE_EXIT_MODE_AB: '1',
        PAPER_LIVE_EXIT_MODE_B_TRAIL_DROP: '0.12',
        PAPER_LIVE_EXIT_MODE_B_TRAIL_TRIGGER_X: '1.06',
        PAPER_LIVE_EXIT_MODE_B_TIMEOUT_HOURS: '4',
        /** Spec V2.1 §5.3 — kill после усреднения в режиме B: −12% к avg (было −8%). */
        PAPER_LIVE_EXIT_MODE_B_DCA_KILLSTOP: '-0.12',
        /** Докуп режима B при −6% к avg (было −4% в коде по умолчанию). */
        PAPER_IDEALIZED_OSCAR_MODE_B_ARM_FRAC: '-0.06',
        PAPER_LIVE_EXIT_MODE_B_TP_GRID_STEP_PNL: '0.05',
        PAPER_LIVE_EXIT_MODE_B_TP_GRID_SELL_FRACTION: '0.50',
        PAPER_LIVE_EXIT_MODE_B_TP_GRID_FIRST_RUNG_RETRACE_MIN_PNL: '0.02',
        PAPER_LIVE_EXIT_MODE_B_TP_GRID_MAX_RUNGS: '4',
        PAPER_DCA_LEVELS: '',
        PAPER_DCA_KILLSTOP: '-0.05',
        PAPER_TP_LADDER: '',
        PAPER_TP_GRID_STEP_PNL: '0.05',
        PAPER_TP_GRID_SELL_FRACTION: '0.15',
        PAPER_TP_GRID_FIRST_RUNG_RETRACE_MIN_PNL: '0.025',
        PAPER_TP_X: '100',
        PAPER_SL_X: '0',
        PAPER_TRAIL_MODE: 'ladder_retrace',
        PAPER_TRAIL_DROP: '0.10',
        PAPER_TRAIL_TRIGGER_X: '1.10',
        PAPER_TIMEOUT_HOURS: '8',
        PAPER_PEAK_LOG_STEP_PCT: '1',
        PAPER_DIP_WHALE_ANALYSIS_ENABLED: '1',
        PAPER_DIP_REQUIRE_WHALE_TRIGGER: '0',
        PAPER_DIP_LARGE_SELL_USD: '3000',
        PAPER_DIP_RECENT_LOOKBACK_MIN: '10',
        PAPER_DIP_CAPITULATION_PCT: '0.7',
        PAPER_DIP_WHALE_SILENCE_MIN: '10',
        PAPER_DIP_GROUP_SELL_USD: '5000',
        PAPER_DIP_GROUP_MIN_SELLERS: '2',
        PAPER_DIP_GROUP_DUMP_PCT: '0.4',
        PAPER_DIP_BLOCK_CREATOR_DUMP: '1',
        PAPER_DIP_CREATOR_DUMP_LOOKBACK_MIN: '20',
        PAPER_DIP_CREATOR_DUMP_MIN_PCT: '0.05',
        PAPER_DIP_CREATOR_DUMP_MAX_PCT: '0.6',
        PAPER_DIP_DCA_PRED_MIN_SELLS_24H: '4',
        PAPER_DIP_DCA_PRED_MIN_INTERVAL_MIN: '30',
        PAPER_DIP_DCA_PRED_MIN_CHUNK_USD: '3000',
        PAPER_DIP_DCA_AGGR_MIN_SELLS_24H: '6',
        PAPER_DIP_DCA_AGGR_MAX_INTERVAL_MIN: '15',
        PAPER_HOLDERS_LIVE_ENABLED: '0',
        PAPER_HOLDERS_USE_QN_ADDON: '0',
        PAPER_HOLDERS_TTL_MS: '90000',
        PAPER_HOLDERS_NEG_TTL_MS: '15000',
        PAPER_HOLDERS_MAX_PER_TICK: '10',
        PAPER_HOLDERS_TIMEOUT_MS: '4000',
        PAPER_HOLDERS_INCLUDE_TOKEN2022: '1',
        PAPER_HOLDERS_ON_FAIL: 'db_fallback',
        PAPER_HOLDERS_DB_WRITEBACK: '1',
        PAPER_HOLDERS_SNAPSHOT_WARMUP_MAX: '12',
        PAPER_HOLDERS_GPA_CREDITS_PER_CALL: '100',
        QN_FEATURE_BUDGET_HOLDERS: '10000000',
        PAPER_PRICE_VERIFY_ENABLED: '1',
        PAPER_PRICE_VERIFY_BLOCK_ON_FAIL: '1',
        PAPER_PRICE_VERIFY_USE_JUPITER_PRICE: '0',
        PAPER_PRICE_VERIFY_MAX_SLIP_PCT: '4.0',
        PAPER_PRICE_VERIFY_MAX_SLIP_BPS: '400',
        PAPER_PRICE_VERIFY_MAX_PRICE_IMPACT_PCT: '8.0',
        PAPER_PRICE_VERIFY_TIMEOUT_MS: '2500',
        PAPER_PRICE_VERIFY_EXIT_ENABLED: '1',
        PAPER_PRICE_VERIFY_EXIT_BLOCK_ON_FAIL: '1',
        PAPER_PRICE_VERIFY_EXIT_MAX_DEFERS_ESCALATION: '60',
        PAPER_SIM_AUDIT_ENABLED: '1',
        PAPER_SIM_SAMPLE_PCT: '5',
        PAPER_SIM_MAX_WALL_MS: '8000',
        PAPER_SIM_BUILD_TIMEOUT_MS: '5000',
        PAPER_SIM_USE_JUPITER_BUILD: '1',
        PAPER_SIM_CREDS_PER_CALL: '30',
        PAPER_SIM_STRICT_BUDGET: '1',
        PAPER_IMPULSE_CONFIRM_ENABLED: '1',
        PAPER_IMPULSE_DIP_POLICY: 'parallel_and',
        PAPER_IMPULSE_PG_MIN_DROP_PCT: '12',
        PAPER_IMPULSE_RPC_MAX_PER_MIN: '30',
        QN_FEATURE_BUDGET_IMPULSE_CONFIRM: '5000000',
        IMPULSE_QN_ROLLING_MAX_CREDITS: '1000000',
        PAPER_LIQ_WATCH_ENABLED: '1',
        PAPER_LIQ_WATCH_FORCE_CLOSE: '1',
        PAPER_LIQ_WATCH_DRAIN_PCT: '35',
        PAPER_LIQ_WATCH_MIN_AGE_MIN: '1',
        PAPER_LIQ_WATCH_CONSECUTIVE_FAILURES: '2',
        PAPER_LIQ_WATCH_SNAPSHOT_MAX_AGE_MS: '120000',
        PAPER_LIQ_WATCH_RPC_FALLBACK: '0',
        PAPER_LIQ_WATCH_STAMP_ON_ALL_CLOSE: '1',
        PAPER_LIQ_WATCH_STAMP_ON_TRACK: '0',
        LIVE_ENTRY_SCALE_IN_ENABLED: '1',
        LIVE_ENTRY_SCALE_IN_DELAY_MS: '5000',
        LIVE_ENTRY_SCALE_IN_CORRIDOR_UP_PCT: '1',
        LIVE_ENTRY_SCALE_IN_CORRIDOR_DOWN_PCT: '2',
        LIVE_ENTRY_SCALE_IN_OUT_OF_CORRIDOR_POLL_MS: '30000',
        LIVE_ENTRY_SCALE_IN_MAX_SWAP_ATTEMPTS: '8',
        LIVE_ENTRY_SCALE_IN_RETRY_BACKOFF_MS: '2000',
      },
    },
    /**
     * Paper Oscar V2.2 — тот же движок выходов, что **paper-oscar-v21** (IDEALIZED V2.1); более рискованный вход (ниже пороги ликвидности / холдеров / объёмов).
     */
    {
      name: 'paper-oscar-v22',
      cwd: root,
      script: 'npm',
      args: 'run --silent paper-oscar-v22',
      interpreter: 'none',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
      max_memory_restart: '200M',
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: 'production',
        PAPER_STRATEGY_KIND: 'dip',
        PAPER_STRATEGY_ID: 'paper-oscar-v22',
        PAPER_TRADES_PATH: path.join(root, 'data/paper2/paper-oscar-v22.jsonl'),
        PAPER_HEARTBEAT_INTERVAL_MS: '30000',
        PAPER_DISCOVERY_INTERVAL_MS: '10000',
        PAPER_TRACK_INTERVAL_MS: '30000',
        PAPER_FOLLOWUP_TICK_MS: '60000',
        PAPER_DRY_RUN: 'false',
        PAPER_POSITION_USD: '120',
        PAPER_ENTRY_FIRST_LEG_FRACTION: '0.75',
        PAPER_SAFETY_CHECK_ENABLED: '1',
        PAPER_PRIORITY_FEE_ENABLED: '1',
        PAPER_PRIORITY_FEE_TICKER_MS: '60000',
        PAPER_PRIORITY_FEE_MAX_AGE_MS: '600000',
        PAPER_PRIORITY_FEE_RPC_TIMEOUT_MS: '2500',
        PAPER_PRIORITY_FEE_PERCENTILE: 'p75',
        PAPER_PRIORITY_FEE_TARGET_CU: '200000',
        PAPER_PRIORITY_FEE_CACHE_PATH: path.join(root, 'data/priority-fee-cache-paper-oscar-v22.json'),
        PAPER_LIVE_MCAP_TTL_MS: '30000',
        PAPER_ENABLE_LAUNCHPAD_LANE: 'false',
        PAPER_ENABLE_MIGRATION_LANE: 'false',
        PAPER_ENABLE_POST_LANE: 'true',
        PAPER_POST_MIN_AGE_MIN: '2160',
        PAPER_POST_MAX_AGE_MIN: '0',
        PAPER_POST_MIN_LIQ_USD: '100000',
        PAPER_POST_MIN_VOL_5M_USD: '10000',
        PAPER_POST_MIN_BUYS_5M: '4',
        PAPER_POST_MIN_SELLS_5M: '3',
        PAPER_POST_MIN_BS: '0.98',
        PAPER_VOL_5M_1H_GUARD_ENABLED: '1',
        PAPER_VOL_1H_MIN_USD: '30000',
        PAPER_VOL_5M_SPIKE_MAX_MULT: '7',
        PAPER_MIN_HOLDER_COUNT: '1000',
        PAPER_DIP_LOOKBACK_MIN: '120',
        PAPER_DIP_LOOKBACK_WINDOWS_MIN: '120,360,720',
        PAPER_DIP_MIN_DROP_PCT: '-15',
        PAPER_DIP_MAX_DROP_PCT: '-50',
        PAPER_DIP_MIN_IMPULSE_PCT: '12',
        PAPER_DIP_MIN_AGE_MIN: '0',
        /** Бумага: без кулдауна entry→entry и без post-exit паузы. */
        PAPER_DIP_COOLDOWN_MIN: '0',
        PAPER_DIP_COOLDOWN_MIN_SCALP: '0',
        PAPER_DIP_LOSS_EXIT_COOLDOWN_ENABLED: 'false',
        PAPER_DIP_LOSS_EXIT_COOLDOWN_MINUTES: '0',
        PAPER_DIP_LOSS_EXIT_COOLDOWN_HOURS: '0',
        PAPER_DIP_RECOVERY_VETO_ENABLED: '1',
        PAPER_DIP_RECOVERY_VETO_WINDOWS_MIN: '30,60',
        PAPER_DIP_RECOVERY_VETO_MAX_BOUNCE_PCT: '12',
        PAPER_TP_REGIME_ENABLED: '0',
        PAPER_LIVE_EXIT_MODE_AB: '1',
        PAPER_LIVE_EXIT_MODE_B_TRAIL_DROP: '0.12',
        PAPER_LIVE_EXIT_MODE_B_TRAIL_TRIGGER_X: '1.06',
        PAPER_LIVE_EXIT_MODE_B_TIMEOUT_HOURS: '4',
        /** Kill после усреднения в режиме B: −12% к avg (было −8%). */
        PAPER_LIVE_EXIT_MODE_B_DCA_KILLSTOP: '-0.12',
        /** Докуп режима B при −6% к avg (было −4%). */
        PAPER_IDEALIZED_OSCAR_MODE_B_ARM_FRAC: '-0.06',
        PAPER_LIVE_EXIT_MODE_B_TP_GRID_STEP_PNL: '0.05',
        PAPER_LIVE_EXIT_MODE_B_TP_GRID_SELL_FRACTION: '0.50',
        PAPER_LIVE_EXIT_MODE_B_TP_GRID_FIRST_RUNG_RETRACE_MIN_PNL: '0.02',
        PAPER_LIVE_EXIT_MODE_B_TP_GRID_MAX_RUNGS: '4',
        PAPER_DCA_LEVELS: '',
        PAPER_DCA_KILLSTOP: '-0.05',
        PAPER_TP_LADDER: '',
        PAPER_TP_GRID_STEP_PNL: '0.05',
        PAPER_TP_GRID_SELL_FRACTION: '0.15',
        PAPER_TP_GRID_FIRST_RUNG_RETRACE_MIN_PNL: '0.025',
        PAPER_TP_X: '100',
        PAPER_SL_X: '0',
        PAPER_TRAIL_MODE: 'ladder_retrace',
        PAPER_TRAIL_DROP: '0.10',
        PAPER_TRAIL_TRIGGER_X: '1.10',
        PAPER_TIMEOUT_HOURS: '8',
        PAPER_PEAK_LOG_STEP_PCT: '1',
        PAPER_DIP_WHALE_ANALYSIS_ENABLED: '1',
        PAPER_DIP_REQUIRE_WHALE_TRIGGER: '0',
        PAPER_DIP_LARGE_SELL_USD: '3000',
        PAPER_DIP_RECENT_LOOKBACK_MIN: '10',
        PAPER_DIP_CAPITULATION_PCT: '0.7',
        PAPER_DIP_WHALE_SILENCE_MIN: '10',
        PAPER_DIP_GROUP_SELL_USD: '5000',
        PAPER_DIP_GROUP_MIN_SELLERS: '2',
        PAPER_DIP_GROUP_DUMP_PCT: '0.4',
        PAPER_DIP_BLOCK_CREATOR_DUMP: '1',
        PAPER_DIP_CREATOR_DUMP_LOOKBACK_MIN: '20',
        PAPER_DIP_CREATOR_DUMP_MIN_PCT: '0.05',
        PAPER_DIP_CREATOR_DUMP_MAX_PCT: '0.6',
        PAPER_DIP_DCA_PRED_MIN_SELLS_24H: '4',
        PAPER_DIP_DCA_PRED_MIN_INTERVAL_MIN: '30',
        PAPER_DIP_DCA_PRED_MIN_CHUNK_USD: '3000',
        PAPER_DIP_DCA_AGGR_MIN_SELLS_24H: '6',
        PAPER_DIP_DCA_AGGR_MAX_INTERVAL_MIN: '15',
        PAPER_HOLDERS_LIVE_ENABLED: '0',
        PAPER_HOLDERS_USE_QN_ADDON: '0',
        PAPER_HOLDERS_TTL_MS: '90000',
        PAPER_HOLDERS_NEG_TTL_MS: '15000',
        PAPER_HOLDERS_MAX_PER_TICK: '10',
        PAPER_HOLDERS_TIMEOUT_MS: '4000',
        PAPER_HOLDERS_INCLUDE_TOKEN2022: '1',
        PAPER_HOLDERS_ON_FAIL: 'db_fallback',
        PAPER_HOLDERS_DB_WRITEBACK: '1',
        PAPER_HOLDERS_SNAPSHOT_WARMUP_MAX: '12',
        PAPER_HOLDERS_GPA_CREDITS_PER_CALL: '100',
        QN_FEATURE_BUDGET_HOLDERS: '10000000',
        PAPER_PRICE_VERIFY_ENABLED: '1',
        PAPER_PRICE_VERIFY_BLOCK_ON_FAIL: '1',
        PAPER_PRICE_VERIFY_USE_JUPITER_PRICE: '0',
        PAPER_PRICE_VERIFY_MAX_SLIP_PCT: '4.0',
        PAPER_PRICE_VERIFY_MAX_SLIP_BPS: '400',
        PAPER_PRICE_VERIFY_MAX_PRICE_IMPACT_PCT: '8.0',
        PAPER_PRICE_VERIFY_TIMEOUT_MS: '2500',
        PAPER_PRICE_VERIFY_EXIT_ENABLED: '1',
        PAPER_PRICE_VERIFY_EXIT_BLOCK_ON_FAIL: '1',
        PAPER_PRICE_VERIFY_EXIT_MAX_DEFERS_ESCALATION: '60',
        PAPER_SIM_AUDIT_ENABLED: '1',
        PAPER_SIM_SAMPLE_PCT: '5',
        PAPER_SIM_MAX_WALL_MS: '8000',
        PAPER_SIM_BUILD_TIMEOUT_MS: '5000',
        PAPER_SIM_USE_JUPITER_BUILD: '1',
        PAPER_SIM_CREDS_PER_CALL: '30',
        PAPER_SIM_STRICT_BUDGET: '1',
        PAPER_IMPULSE_CONFIRM_ENABLED: '1',
        PAPER_IMPULSE_DIP_POLICY: 'parallel_and',
        PAPER_IMPULSE_PG_MIN_DROP_PCT: '12',
        PAPER_IMPULSE_RPC_MAX_PER_MIN: '30',
        QN_FEATURE_BUDGET_IMPULSE_CONFIRM: '5000000',
        IMPULSE_QN_ROLLING_MAX_CREDITS: '1000000',
        PAPER_LIQ_WATCH_ENABLED: '1',
        PAPER_LIQ_WATCH_FORCE_CLOSE: '1',
        PAPER_LIQ_WATCH_DRAIN_PCT: '35',
        PAPER_LIQ_WATCH_MIN_AGE_MIN: '1',
        PAPER_LIQ_WATCH_CONSECUTIVE_FAILURES: '2',
        PAPER_LIQ_WATCH_SNAPSHOT_MAX_AGE_MS: '120000',
        PAPER_LIQ_WATCH_RPC_FALLBACK: '0',
        PAPER_LIQ_WATCH_STAMP_ON_ALL_CLOSE: '1',
        PAPER_LIQ_WATCH_STAMP_ON_TRACK: '0',
        LIVE_ENTRY_SCALE_IN_ENABLED: '1',
        LIVE_ENTRY_SCALE_IN_DELAY_MS: '5000',
        LIVE_ENTRY_SCALE_IN_CORRIDOR_UP_PCT: '1',
        LIVE_ENTRY_SCALE_IN_CORRIDOR_DOWN_PCT: '2',
        LIVE_ENTRY_SCALE_IN_OUT_OF_CORRIDOR_POLL_MS: '30000',
        LIVE_ENTRY_SCALE_IN_MAX_SWAP_ATTEMPTS: '8',
        LIVE_ENTRY_SCALE_IN_RETRY_BACKOFF_MS: '2000',
      },
    },
  ],
};
