#!/usr/bin/env bash
# Точка входа для PM2: см. ecosystem.market-pullback-watch.cjs
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

export NODE_ENV="${NODE_ENV:-production}"
export PULLBACK_ALERT_POLL_INTERVAL_MS="${PULLBACK_ALERT_POLL_INTERVAL_MS:-20000}"
export PULLBACK_ALERT_POLL_SEND_DEDUPE_MS="${PULLBACK_ALERT_POLL_SEND_DEDUPE_MS:-120000}"
export PULLBACK_ALERT_MINT_COOLDOWN_MINUTES="${PULLBACK_ALERT_MINT_COOLDOWN_MINUTES:-30}"
export PULLBACK_ALERT_SCAN_MINUTES="${PULLBACK_ALERT_SCAN_MINUTES:-90}"
export PULLBACK_ALERT_MIN_RISE_PCT="${PULLBACK_ALERT_MIN_RISE_PCT:-6}"
export PULLBACK_ALERT_MIN_RETRACE_FROM_PEAK_PCT="${PULLBACK_ALERT_MIN_RETRACE_FROM_PEAK_PCT:-10}"
export PULLBACK_ALERT_MIN_HOLDERS="${PULLBACK_ALERT_MIN_HOLDERS:-1000}"
export PULLBACK_ALERT_HOLDER_NULL_SOFT="${PULLBACK_ALERT_HOLDER_NULL_SOFT:-1}"
export PULLBACK_ALERT_MIN_AGE_HOURS="${PULLBACK_ALERT_MIN_AGE_HOURS:-3}"
export PULLBACK_ALERT_MAX_ROWS_PER_TABLE="${PULLBACK_ALERT_MAX_ROWS_PER_TABLE:-800}"
export PULLBACK_ALERT_MIN_LIQ_USD="${PULLBACK_ALERT_MIN_LIQ_USD:-0}"
export PULLBACK_ALERT_MIN_MARKET_CAP_USD="${PULLBACK_ALERT_MIN_MARKET_CAP_USD:-1500000}"
export PULLBACK_ALERT_MIN_VOL_5M_USD="${PULLBACK_ALERT_MIN_VOL_5M_USD:-0}"
export PULLBACK_ALERT_DRY_RUN="${PULLBACK_ALERT_DRY_RUN:-0}"
export PULLBACK_ALERT_MAX_NEWER_BAR_AGE_MINUTES="${PULLBACK_ALERT_MAX_NEWER_BAR_AGE_MINUTES:-25}"
export PULLBACK_ALERT_DISPLAY_TZ="${PULLBACK_ALERT_DISPLAY_TZ:-Europe/Moscow}"

exec npm run --silent market-pullback-telegram-watch
