#!/usr/bin/env bash
# Устар.: канон — ecosystem.config.cjs (`retrace-alert-watch`). Скрипт оставлен для ручного dev.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

export NODE_ENV="${NODE_ENV:-production}"
RETRACE_TG_CHAT_DEFAULT='-1003878024799'
export RETRACE_ALERT_TELEGRAM_CHAT_ID="${RETRACE_ALERT_TELEGRAM_CHAT_ID:-$RETRACE_TG_CHAT_DEFAULT}"
export RETRACE_ALERT_POLL_INTERVAL_MS="${RETRACE_ALERT_POLL_INTERVAL_MS:-20000}"
export RETRACE_ALERT_POLL_SEND_DEDUPE_MS="${RETRACE_ALERT_POLL_SEND_DEDUPE_MS:-120000}"
export RETRACE_PULLBACK_CHANNEL_DEDUPE_PEAK_BUCKET_MIN="${RETRACE_PULLBACK_CHANNEL_DEDUPE_PEAK_BUCKET_MIN:-15}"
export RETRACE_ALERT_MINT_COOLDOWN_MINUTES="${RETRACE_ALERT_MINT_COOLDOWN_MINUTES:-30}"
export RETRACE_ALERT_SCAN_MINUTES="${RETRACE_ALERT_SCAN_MINUTES:-120}"
export RETRACE_ALERT_MIN_MCAP_USD="${RETRACE_ALERT_MIN_MCAP_USD:-1000000}"
export RETRACE_ALERT_MIN_PUMP_PCT="${RETRACE_ALERT_MIN_PUMP_PCT:-6}"
export RETRACE_ALERT_MIN_RETRACE_FROM_PEAK_PCT="${RETRACE_ALERT_MIN_RETRACE_FROM_PEAK_PCT:-10}"
export RETRACE_ALERT_MAX_EVENT_AGE_MINUTES="${RETRACE_ALERT_MAX_EVENT_AGE_MINUTES:-15}"
export RETRACE_ALERT_MAX_ROWS_PER_TABLE="${RETRACE_ALERT_MAX_ROWS_PER_TABLE:-800}"
export RETRACE_ALERT_MIN_AGE_HOURS="${RETRACE_ALERT_MIN_AGE_HOURS:-8}"
export RETRACE_ALERT_MIN_HOLDERS="${RETRACE_ALERT_MIN_HOLDERS:-0}"
export RETRACE_ALERT_HOLDER_NULL_SOFT="${RETRACE_ALERT_HOLDER_NULL_SOFT:-1}"
export RETRACE_ALERT_DISPLAY_TZ="${RETRACE_ALERT_DISPLAY_TZ:-Europe/Moscow}"
export RETRACE_ALERT_DRY_RUN="${RETRACE_ALERT_DRY_RUN:-0}"

exec npm run --silent retrace-alert-watch
