#!/usr/bin/env bash
# Точка входа для PM2: см. ecosystem.market-spike-watch.cjs (PM2 6 на VPS не парсит этот .cjs как ecosystem).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

export NODE_ENV="${NODE_ENV:-production}"
export SPIKE_ALERT_POLL_INTERVAL_MS="${SPIKE_ALERT_POLL_INTERVAL_MS:-20000}"
export SPIKE_ALERT_POLL_SEND_DEDUPE_MS="${SPIKE_ALERT_POLL_SEND_DEDUPE_MS:-60000}"
export SPIKE_ALERT_MINT_COOLDOWN_MINUTES="${SPIKE_ALERT_MINT_COOLDOWN_MINUTES:-5}"
export SPIKE_ALERT_SCAN_MINUTES="${SPIKE_ALERT_SCAN_MINUTES:-60}"
export SPIKE_ALERT_ROLLING_MINUTES="${SPIKE_ALERT_ROLLING_MINUTES:-3}"
export SPIKE_ALERT_ROLLING_MAX_MINUTES="${SPIKE_ALERT_ROLLING_MAX_MINUTES:-10}"
export SPIKE_ALERT_THRESHOLD_PCT="${SPIKE_ALERT_THRESHOLD_PCT:-8}"
export SPIKE_ALERT_THRESHOLD_PUMP_CONSEC_PCT="${SPIKE_ALERT_THRESHOLD_PUMP_CONSEC_PCT:-8}"
export SPIKE_ALERT_THRESHOLD_DUMP_CONSEC_PCT="${SPIKE_ALERT_THRESHOLD_DUMP_CONSEC_PCT:-8}"
export SPIKE_ALERT_THRESHOLD_ROLLING_PCT="${SPIKE_ALERT_THRESHOLD_ROLLING_PCT:-10}"
export SPIKE_ALERT_MIN_HOLDERS="${SPIKE_ALERT_MIN_HOLDERS:-1000}"
export SPIKE_ALERT_HOLDER_NULL_SOFT="${SPIKE_ALERT_HOLDER_NULL_SOFT:-1}"
export SPIKE_ALERT_MIN_AGE_HOURS="${SPIKE_ALERT_MIN_AGE_HOURS:-3}"
export SPIKE_ALERT_MAX_ROWS_PER_TABLE="${SPIKE_ALERT_MAX_ROWS_PER_TABLE:-800}"
export SPIKE_ALERT_MIN_LIQ_USD="${SPIKE_ALERT_MIN_LIQ_USD:-0}"
export SPIKE_ALERT_MIN_MARKET_CAP_USD="${SPIKE_ALERT_MIN_MARKET_CAP_USD:-2000000}"
export SPIKE_ALERT_MIN_VOL_5M_USD="${SPIKE_ALERT_MIN_VOL_5M_USD:-0}"
export SPIKE_ALERT_DRY_RUN="${SPIKE_ALERT_DRY_RUN:-0}"
export SPIKE_ALERT_MAX_NEWER_BAR_AGE_MINUTES="${SPIKE_ALERT_MAX_NEWER_BAR_AGE_MINUTES:-20}"
export SPIKE_ALERT_LOW_LIQ_GLITCH_THRESHOLD_USD="${SPIKE_ALERT_LOW_LIQ_GLITCH_THRESHOLD_USD:-5000}"
export SPIKE_ALERT_LOW_LIQ_MAX_ABS_PCT="${SPIKE_ALERT_LOW_LIQ_MAX_ABS_PCT:-55}"
export SPIKE_ALERT_DISPLAY_TZ="${SPIKE_ALERT_DISPLAY_TZ:-Europe/Moscow}"
export SPIKE_ALERT_GLITCH_NEXT_BAR_RETRACE_MIN="${SPIKE_ALERT_GLITCH_NEXT_BAR_RETRACE_MIN:-0.55}"
export SPIKE_ALERT_LIQ_MCAP_SANITY="${SPIKE_ALERT_LIQ_MCAP_SANITY:-1}"
export SPIKE_ALERT_LIQ_MCAP_REF_MIN_USD="${SPIKE_ALERT_LIQ_MCAP_REF_MIN_USD:-2000000}"
export SPIKE_ALERT_MIN_LIQ_TO_REF_MCAP_RATIO="${SPIKE_ALERT_MIN_LIQ_TO_REF_MCAP_RATIO:-0.002}"
export SPIKE_ALERT_MC_PRICE_MAX_DIVERGENCE_PCT="${SPIKE_ALERT_MC_PRICE_MAX_DIVERGENCE_PCT:-8}"
export SPIKE_ALERT_DEXSCREENER_META="${SPIKE_ALERT_DEXSCREENER_META:-1}"
export SPIKE_ALERT_UPSERT_TOKEN_META="${SPIKE_ALERT_UPSERT_TOKEN_META:-1}"

# Tier-каскад по market cap (см. ecosystem.market-spike-watch.cjs/комментарии).
export SPIKE_ALERT_TIERED_BY_MCAP="${SPIKE_ALERT_TIERED_BY_MCAP:-1}"
export SPIKE_ALERT_PUMP_MIN_PCT="${SPIKE_ALERT_PUMP_MIN_PCT:-30}"
export SPIKE_ALERT_DUMP_TIER1_MCAP_USD="${SPIKE_ALERT_DUMP_TIER1_MCAP_USD:-1500000}"
export SPIKE_ALERT_DUMP_TIER1_MIN_PCT="${SPIKE_ALERT_DUMP_TIER1_MIN_PCT:-14}"
export SPIKE_ALERT_DUMP_TIER1_MIN_PCT_ROLLING="${SPIKE_ALERT_DUMP_TIER1_MIN_PCT_ROLLING:-15}"
export SPIKE_ALERT_DUMP_TIER2_MCAP_USD="${SPIKE_ALERT_DUMP_TIER2_MCAP_USD:-3000000}"
export SPIKE_ALERT_DUMP_TIER2_MIN_PCT="${SPIKE_ALERT_DUMP_TIER2_MIN_PCT:-11}"
export SPIKE_ALERT_DUMP_TIER2_MIN_PCT_ROLLING="${SPIKE_ALERT_DUMP_TIER2_MIN_PCT_ROLLING:-12}"
export SPIKE_ALERT_DUMP_TIER3_MCAP_USD="${SPIKE_ALERT_DUMP_TIER3_MCAP_USD:-7000000}"
export SPIKE_ALERT_DUMP_TIER3_MIN_PCT="${SPIKE_ALERT_DUMP_TIER3_MIN_PCT:-8}"
export SPIKE_ALERT_DUMP_TIER3_MIN_PCT_ROLLING="${SPIKE_ALERT_DUMP_TIER3_MIN_PCT_ROLLING:-10}"
export SPIKE_ALERT_LOG_MISS_BY_FILTER="${SPIKE_ALERT_LOG_MISS_BY_FILTER:-1}"

# Эскалация: повторный [UPDATE]-алерт при усилении пролива внутри cooldown.
export SPIKE_ALERT_ESCALATE_ENABLED="${SPIKE_ALERT_ESCALATE_ENABLED:-1}"
export SPIKE_ALERT_ESCALATE_DELTA_PCT="${SPIKE_ALERT_ESCALATE_DELTA_PCT:-5}"
export SPIKE_ALERT_ESCALATE_MIN_GAP_SEC="${SPIKE_ALERT_ESCALATE_MIN_GAP_SEC:-60}"
export SPIKE_ALERT_ESCALATE_MAX_PER_MINT="${SPIKE_ALERT_ESCALATE_MAX_PER_MINT:-3}"
export SPIKE_ALERT_ESCALATE_TIER_CHANGE_FORCES_UPDATE="${SPIKE_ALERT_ESCALATE_TIER_CHANGE_FORCES_UPDATE:-1}"

# Аудит решений в PG-таблице market_spike_events (graceful fallback в stdout).
export SPIKE_ALERT_AUDIT_DB_ENABLED="${SPIKE_ALERT_AUDIT_DB_ENABLED:-1}"
export SPIKE_ALERT_AUDIT_LOG_SKIPS="${SPIKE_ALERT_AUDIT_LOG_SKIPS:-0}"

exec npm run --silent market-spike-telegram-watch
