#!/usr/bin/env bash
# PM2 6 does not parse ecosystem.vol-green.cjs as an ecosystem file — use this entry.
#   pm2 start scripts/vol-green-pm2-entry.sh --name vol-green-bot --interpreter bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

if [[ -f "$ROOT/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  . "$ROOT/.env"
  set +a
fi

export NODE_ENV="${NODE_ENV:-production}"
export VOL_GREEN_APP_NAME="${VOL_GREEN_APP_NAME:-vol-green-bot}"
export VOL_GREEN_ENTRY_MODE="${VOL_GREEN_ENTRY_MODE:-awakening}"
export VOL_GREEN_EXECUTION_MODE="${VOL_GREEN_EXECUTION_MODE:-live}"
export VOL_GREEN_WALLET_SECRET="${VOL_GREEN_WALLET_SECRET:-$ROOT/data/live/copy-8zkg.keypair.json}"
export VOL_GREEN_WALLET_PUBKEY="${VOL_GREEN_WALLET_PUBKEY:-FxQfFTmj6xfjbzE2LcXteJMjd1KpBjMhH9nzEiijUGHX}"
export VOL_GREEN_POSITION_USD="${VOL_GREEN_POSITION_USD:-5}"
export VOL_GREEN_MAX_OPEN_POSITIONS="${VOL_GREEN_MAX_OPEN_POSITIONS:-0}"
export VOL_GREEN_JOURNAL_PATH="${VOL_GREEN_JOURNAL_PATH:-$ROOT/data/volgreen/journal.jsonl}"
export VOL_GREEN_STATE_PATH="${VOL_GREEN_STATE_PATH:-$ROOT/data/volgreen/state.json}"
export VOL_GREEN_HOT_MINTS_PATH="${VOL_GREEN_HOT_MINTS_PATH:-$ROOT/data/volgreen/hot-mints.json}"
export VOL_GREEN_PRICE_RING_PATH="${VOL_GREEN_PRICE_RING_PATH:-$ROOT/data/volgreen/price-ring.json}"
export VOL_GREEN_EXIT_ARM_PCT="${VOL_GREEN_EXIT_ARM_PCT:-8}"
export VOL_GREEN_EXIT_GIVEBACK_PCT="${VOL_GREEN_EXIT_GIVEBACK_PCT:-6}"
export VOL_GREEN_EXIT_NEVER_ARM_PATIENCE_MS="${VOL_GREEN_EXIT_NEVER_ARM_PATIENCE_MS:-0}"
export VOL_GREEN_EXIT_NEVER_ARM_DEAD_MIN_MS="${VOL_GREEN_EXIT_NEVER_ARM_DEAD_MIN_MS:-900000}"
export VOL_GREEN_EXIT_NEVER_ARM_DEAD_PNL_PCT="${VOL_GREEN_EXIT_NEVER_ARM_DEAD_PNL_PCT:-15}"
export VOL_GREEN_EXIT_NEVER_ARM_VOL_FADE_MIN_MS="${VOL_GREEN_EXIT_NEVER_ARM_VOL_FADE_MIN_MS:-600000}"
export VOL_GREEN_EXIT_NEVER_ARM_VOL_FADE_RATIO="${VOL_GREEN_EXIT_NEVER_ARM_VOL_FADE_RATIO:-0.35}"
export VOL_GREEN_EXIT_NEVER_ARM_VOL_FADE_FLOOR_USD="${VOL_GREEN_EXIT_NEVER_ARM_VOL_FADE_FLOOR_USD:-500}"
export VOL_GREEN_EXIT_NEVER_ARM_MAX_HOLD_MS="${VOL_GREEN_EXIT_NEVER_ARM_MAX_HOLD_MS:-5400000}"
export VOL_GREEN_SLIPPAGE_BPS="${VOL_GREEN_SLIPPAGE_BPS:-500}"
export VOL_GREEN_MAX_CHASE_PCT="${VOL_GREEN_MAX_CHASE_PCT:-4}"
export VOL_GREEN_ALLOWED_DEX_IDS="${VOL_GREEN_ALLOWED_DEX_IDS:-pumpswap,pumpfun,raydium}"
export VOL_GREEN_DISCOVER_SOURCES="${VOL_GREEN_DISCOVER_SOURCES:-stream}"
export VOL_GREEN_STREAM="${VOL_GREEN_STREAM:-1}"
export VOL_GREEN_MIN_FEE_SOL_RESERVE="${VOL_GREEN_MIN_FEE_SOL_RESERVE:-0.02}"
export MILD_DIP_DISCOVER_SOURCES="${MILD_DIP_DISCOVER_SOURCES:-$VOL_GREEN_DISCOVER_SOURCES}"
export MILD_DIP_ENRICH_CONCURRENCY="${MILD_DIP_ENRICH_CONCURRENCY:-4}"
export DEXSCREENER_GATE_ENABLED="${DEXSCREENER_GATE_ENABLED:-1}"
export DEXSCREENER_MAX_RPM="${DEXSCREENER_MAX_RPM:-120}"
export JUPITER_GLOBAL_MAX_RPS="${JUPITER_GLOBAL_MAX_RPS:-9}"
export LIVE_BUY_MAX_PRICE_IMPACT_PCT="${LIVE_BUY_MAX_PRICE_IMPACT_PCT:-1}"
export LIVE_JUPITER_SWAP_PRIORITY_LEVEL="${LIVE_JUPITER_SWAP_PRIORITY_LEVEL:-medium}"
export LIVE_JUPITER_PRIORITY_MAX_SOL="${LIVE_JUPITER_PRIORITY_MAX_SOL:-0.00005}"
export SOLANA_RPC_HELIUS_PREFER="${SOLANA_RPC_HELIUS_PREFER:-1}"

if [[ -n "${HELIUS_RPC_URL:-}" ]]; then
  export VOL_GREEN_RPC_URL="${VOL_GREEN_RPC_URL:-$HELIUS_RPC_URL}"
  export MILD_DIP_RPC_URL="${MILD_DIP_RPC_URL:-$HELIUS_RPC_URL}"
  export SA_RPC_HTTP_URL="${SA_RPC_HTTP_URL:-$HELIUS_RPC_URL}"
  export SOLANA_RPC_HTTP_URL="${SOLANA_RPC_HTTP_URL:-$HELIUS_RPC_URL}"
fi

mkdir -p "$(dirname "$VOL_GREEN_JOURNAL_PATH")" "$(dirname "$VOL_GREEN_STATE_PATH")" data/ops-heartbeats

exec npm run --silent vol-green-bot
