#!/usr/bin/env bash
set -euo pipefail
cd /opt/solana-alpha
export DATABASE_URL='postgresql://salpha:f5e4930e0586adf71ca193336415351a6f2ac0f6370c538d@localhost:5432/solana_alpha'
export PAPER_TRADES_PATH='/opt/solana-alpha/data/paper2/pt1_dno_clone.jsonl'
export PAPER_STRATEGY_ID='pt1_dno_clone'
export PAPER_STRATEGY_KIND='fresh_validated'
export PAPER_FV_LABEL='dno_clone'
export PAPER_POSITION_USD=100

# --- Вход = Deep Runner (pt1_dip_runners): post-migration, красная свеча, whale, cooldown
export PAPER_FV_USE_DIP_ENTRY=1
export PAPER_ENABLE_LAUNCHPAD_LANE=0
export PAPER_ENABLE_MIGRATION_LANE=0
export PAPER_ENABLE_POST_LANE=1

export PAPER_POST_MIN_AGE_MIN=180
export PAPER_POST_MAX_AGE_MIN=4320
export PAPER_POST_MIN_LIQ_USD=8000
export PAPER_POST_MIN_VOL_5M_USD=500
export PAPER_POST_MIN_BUYS_5M=4
export PAPER_POST_MIN_SELLS_5M=3
export PAPER_POST_MIN_BS=0.98

export PAPER_DIP_LOOKBACK_MIN=120
export PAPER_DIP_MIN_DROP_PCT=-5
export PAPER_DIP_MAX_DROP_PCT=-30
export PAPER_DIP_MIN_IMPULSE_PCT=12
export PAPER_DIP_MIN_AGE_MIN=180

export PAPER_REEVAL_AFTER_SEC=60
export PAPER_DISCOVERY_INTERVAL_MS=10000

export PAPER_DIP_WHALE_ANALYSIS_ENABLED=1
export PAPER_FV_WHALE_ANALYSIS_ENABLED=0
export PAPER_DIP_REQUIRE_WHALE_TRIGGER=0
export PAPER_DIP_LARGE_SELL_USD=3000
export PAPER_DIP_RECENT_LOOKBACK_MIN=10
export PAPER_DIP_CAPITULATION_PCT=0.7
export PAPER_DIP_GROUP_SELL_USD=5000
export PAPER_DIP_GROUP_MIN_SELLERS=2
export PAPER_DIP_GROUP_DUMP_PCT=0.4
export PAPER_DIP_BLOCK_CREATOR_DUMP=1
export PAPER_DIP_CREATOR_DUMP_LOOKBACK_MIN=20
export PAPER_DIP_CREATOR_DUMP_MIN_PCT=0.05
export PAPER_DIP_CREATOR_DUMP_MAX_PCT=0.6
export PAPER_DIP_DCA_PRED_MIN_SELLS_24H=4
export PAPER_DIP_DCA_PRED_MIN_INTERVAL_MIN=30
export PAPER_DIP_DCA_PRED_MIN_CHUNK_USD=3000
export PAPER_DIP_DCA_AGGR_MIN_SELLS_24H=6
export PAPER_DIP_DCA_AGGR_MAX_INTERVAL_MIN=15

export PAPER_DIP_COOLDOWN_MIN=120
export PAPER_DIP_COOLDOWN_MIN_SCALP=20

# --- Выход = только Dno (без усреднения, короткий скальп)
export PAPER_DCA_LEVELS=''
export PAPER_DCA_KILLSTOP=0

export PAPER_TP_LADDER='0.05:0.30,0.10:0.30,0.20:0.30,0.30:0.10'
export PAPER_TP_X=1.5
export PAPER_SL_X=0.90
export PAPER_TRAIL_DROP=0.05
export PAPER_TRAIL_TRIGGER_X=1.05
export PAPER_TIMEOUT_HOURS=1
export PAPER_PEAK_LOG_STEP_PCT=1

# Вход с DEX — как у dip-runners
export PAPER_FEE_BPS_PER_SIDE=30
export PAPER_SLIPPAGE_BPS_PER_SIDE=120
export PAPER_CONTEXT_SWAPS=1
export PAPER_CONTEXT_SWAPS_LIMIT=5

exec npx tsx scripts-tmp/live-paper-trader.ts
