/**
 * Map MildDipConfig → CopyTraderConfig so we reuse Jupiter USDC buy/sell.
 */
import type { CopyTraderConfig } from '../copytrader/config.js';
import type { MildDipConfig } from './config.js';

/** Dummy leader — required by CopyTraderConfig schema; never polled by this bot. */
export const MILD_DIP_DUMMY_LEADER = 'MildDip11111111111111111111111111111111111';

export function mildDipToCopyTraderConfig(cfg: MildDipConfig): CopyTraderConfig {
  return {
    targetWallet: MILD_DIP_DUMMY_LEADER,
    rpcUrl: cfg.rpcUrl,
    executionMode: cfg.executionMode,
    journalPath: cfg.journalPath,
    statePath: cfg.statePath,
    pollIntervalMs: 12_000,
    signatureLimit: 25,
    leaderStreamEnabled: false,
    leaderStreamPollBackupMs: 15_000,
    leaderStreamFastPollMs: 1_500,
    leaderStreamMissThreshold: 2,
    leaderStreamWatchdogAlertCooldownMs: 300_000,
    leaderIngressConcurrency: 4,
    tickIntervalMs: 2_000,
    buyDelayMs: 0,
    buyDelaySkipMaxPremiumPct: 0,
    entryProbeBuyDelayMs: 0,
    buyRetryWindowMs: 120_000,
    buyRetryDeferLogMs: 60_000,
    buyRetryIntervalMs: 5_000,
    sellRetryWindowMs: 600_000,
    sellRetryIntervalMs: 3_000,
    sellRetryDeferLogMs: 30_000,
    sellMaxAttempts: 40,
    sellMaxUnroutableAttempts: 8,
    sellRetryBackoffMaxMs: 60_000,
    sellAbandonCooldownMs: 600_000,
    dustMinUsd: 1,
    dustMinTokenRaw: 1_000,
    minSellIntervalMs: 500,
    entryDipJupiterMinIntervalMs: 0,
    entryDipUseJupiter: false,
    sellDelayMinMs: 0,
    sellDelayMaxMs: 0,
    sellDelaySkipMaxDropPct: 0,
    leaderFlatConfirmDelayMs: 3_000,
    leaderFlatDustRaw: 10_000n,
    positionUsd: cfg.positionUsd,
    initialMirrorRatio: 0,
    minMirrorEntryUsd: 0,
    addPositionUsd: cfg.positionUsd,
    maxPositionUsd: 0,
    maxAddsPerMint: 0,
    minProportionalAddUsd: 0,
    minProportionalSellFraction: 0,
    /** Align Jupiter premium guard with chase — was hard-tied and killed late fills. */
    buyPriceMaxPremiumPct: cfg.maxChasePct > 0 ? cfg.maxChasePct : 12,
    quotePremiumGuardPct: cfg.maxChasePct > 0 ? cfg.maxChasePct : 12,
    quotePremiumFirstShotPct: 0,
    quotePremiumGraceMs: 0,
    entryFullMcapUsd: 0,
    entryMidPositionUsd: cfg.positionUsd,
    entryMidLegUsd: cfg.positionUsd,
    entryLowMcapMinUsd: 0,
    entryLowMcapMaxUsd: 0,
    entryLowPositionUsd: 0,
    entryLow2McapMinUsd: 0,
    entryLow2McapMaxUsd: 0,
    entryLow2PositionUsd: 0,
    entryProbeFraction: 1,
    entryDipDiscountPct: 0,
    entryDipConfirmTicks: 1,
    entryDipVsProbePct: 0,
    entryMinDeployFraction: 0.99,
    addPriceMaxPremiumPct: 0,
    allowLateEntryOnLeaderRebuy: false,
    enterOnlyOnLeaderAdd: false,
    enterOnLeaderAddBagRatio: 0,
    minLeaderBuyUsd: 0,
    minLiquidityUsd: cfg.entry.minLiquidityUsd,
    minMarketCapUsd: cfg.entry.minMarketCapUsd,
    maxMarketCapUsd: cfg.entry.maxMarketCapUsd,
    minPairAgeHours: 0,
    leaderGatesEnabled: false,
    minLeaderPriorSessions: 0,
    minLeaderPriorAvgPct: 0,
    entryMinPairAgeHours: 0,
    // 1.11.970 — neutral bridge value; mild-dip applies the risk gate before execution.
    ...{ entryMinLiquidityUsd: 0 },
    entryMaxPairAgeHours: 0,
    entryMinBuySellRatio5m: 0,
    entryMaxChase5mPct: 0,
    entryMinTurnover5m: 0,
    entryMinVolToMcap1h: 0,
    entryMinVolume5mUsd: 0,
    shadowSelectEnabled: false,
    shadowSelectFilterLive: false,
    shadowSelectMinVolume5mUsd: 0,
    shadowSelectMinBuySellRatio5m: 0,
    shadowSelectMinMcapUsd: 0,
    shadowSelectMinLiquidityUsd: 0,
    shadowSelectRequireCtx: false,
    shadowSelectSummaryMs: 0,
    leaderHistoryTtlMs: 2_592_000_000,
    trailArmPct: 0,
    trailGivebackPct: 0,
    trailTakeProfitPct: 0,
    trailTpStepPct: 0,
    trailTpSellFraction: 0.5,
    trailTrailSellFraction: 1,
    trailKillPct: 0,
    trailTimeCapMs: 0,
    trailTickIntervalMs: 5_000,
    volFadeCheckIntervalMs: 0,
    volFadeMinVolume5mUsd: 0,
    volFadeDropPct: 0,
    volFadeSampleWindow: 3,
    volFadeMinWeakSamples: 2,
    mirrorEarlyTpGainPct: 0,
    mirrorEarlyTpSellFraction: 0.5,
    mirrorEarlyTpTickIntervalMs: 5_000,
    mirrorHoldCapMs: 0,
    mirrorHoldCapVolOkMs: 0,
    leaderFollowOnlyMinMcapUsd: 0,
    leaderFollowOnlyMinVolume1hUsd: 0,
    maxOpenPositions: cfg.maxOpenPositions,
    quoteAsset: 'USDC',
    minFeeSolReserve: cfg.minFeeSolReserve,
    slippageBps: cfg.slippageBps,
    maxQuoteRegressionPct: 0,
    walletSecret: cfg.walletSecret,
    walletPubkeyExpected: cfg.walletPubkeyExpected,
    sharedOscarWallet: false,
    exitMode: 'mirror',
    spareCapitalGateEnabled: false,
  };
}
